#!/usr/bin/env Rscript

# ==============================================================================
# 03_heatmapLong_effectDonorGroup_FDR005absLog2FC05perCluster_maxPctSeries_4geneSetsFisher19437perCluster_v5.R
#
# Series of five long heatmaps for the main FMT donor-group effect from the
# cluster-specific pseudobulk edgeR two-factor analysis, with additional
# summed GR/MR target-gene repetition annotations from ChEA 2022 and
# one-sided Fisher enrichment tests for four gene sets: GR, MR,
# gr_brain_test and gr_blood_test.
#
# SELECTION
#   FDR < 0.05
#   abs(log2FC) >= 0.5
#
# INPUT
#   Everything is read directly from the RData files generated by the
#   cluster-specific edgeR workflow:
#
#   1. *_edgeRResults.RData
#      - edgeR_perCluster_combinedResults
#      - edgeR_perCluster_testDefinitions
#
#   2. *_edgeRModelObjects.RData
#      - edgeR_perCluster_modelObjects
#      - DGEList for every completed cluster
#      - sample metadata
#      - TMM normalization factors
#
# ROWS
#   Base significant cluster-gene donor-group results satisfying:
#     FDR < 0.05
#     abs(log2FC) >= 0.5
#
#   Five heatmaps are generated from this base result set:
#     1. all      -> no Max mean % filter
#     2. maxPct10 -> Max mean % >= 10
#     3. maxPct15 -> Max mean % >= 15
#     4. maxPct20 -> Max mean % >= 20
#     5. maxPct25 -> Max mean % >= 25
#
#   The same gene can occur more than once when significant in several clusters.
#
# COLUMNS
#   Samples ordered as:
#     Male Neurotypical -> Male ASD -> Female Neurotypical -> Female ASD
#
# HEATMAP VALUES
#   TMM-normalized CPM per sample and cluster
#   -> log2(CPM + 1)
#   -> row-wise Z-score
#   -> clipped to [-2, 2]
#
# ROW CLUSTERING
#   One global hierarchical clustering.
#   Base distance:
#     2 - Pearson correlation
#
#   Rows derived from the same anatomical cluster are made slightly closer,
#   while rows derived from different clusters are made slightly more distant.
#
# RIGHT ANNOTATIONS
#   GR
#     Sum of binary target-gene membership across the three selected GR
#     ChEA 2022 gene sets:
#       0 = absent from all 3 GR sets
#       1 = present in 1/3 GR sets
#       2 = present in 2/3 GR sets
#       3 = present in 3/3 GR sets
#
#   MR
#     Sum of binary target-gene membership across the two selected MR
#     ChEA 2022 gene sets:
#       0 = absent from both MR sets
#       1 = present in 1/2 MR sets
#       2 = present in 2/2 MR sets
#
#   Gene-symbol matching is case-insensitive by converting both heatmap
#   symbols and ChEA symbols to uppercase.
#
# FISHER ENRICHMENT
#   Four gene sets are tested:
#     GR            = union of the three selected GR ChEA 2022 sets
#     MR            = union of the two selected MR ChEA 2022 sets
#     gr_brain_test = manually defined GR brain signature
#     gr_blood_test = manually defined GR blood signature
#
#   For every heatmap variant, one-sided Fisher exact tests
#   (alternative = "greater") are calculated:
#     1. globally for all unique genes displayed on the heatmap
#     2. separately for every source cluster
#
#   Fixed background:
#     19,437 genes for every Fisher contingency table.
#
#   Only global GR/MR Fisher significance is displayed on the heatmap.
#   gr_brain_test, gr_blood_test and all per-cluster Fisher results are written
#   only to TSV files.
#
#   Significance markers:
#     *   p < 0.05
#     **  p < 0.01
#     *** p < 0.001
#
#   Cluster
#     Source Leiden cluster.
#
#   Max mean %
#     Maximum mean percentage of positive spots across:
#       Neurotypical
#       ASD
#
#     For the donor-group main effect, these percentages are already aggregated
#     across sexes in the edgeR result table.
#
#     Percentage is printed directly inside the purple annotation cell.
#     Text colour:
#       <= 70% -> black
#       >  70% -> white
#
#   FDR marker
#       *   FDR < 0.05
#       **  FDR < 0.01
#       *** FDR < 0.001
#
#   |log2FC| marker
#       #   0.5 <= abs(log2FC) < 0.8
#       ##  0.8 <= abs(log2FC) < 1.0
#       ### abs(log2FC) >= 1.0
#
#   n clusters
#     Number of significant source clusters in which the same gene occurs
#     on this heatmap. Genes occurring only once have n clusters = 1.
#
#   Gene symbol
#     Gene symbol with the source-cluster tag, e.g. G3bp1 [C16].
#
# OUTPUT
#   1-5. Five long PDF heatmaps:
#        all, maxPct10, maxPct15, maxPct20, maxPct25.
#   6.   One combined TSV table summarizing the number of displayed
#        cluster-gene results per cluster for every Max mean % variant.
#
# IMPORTANT
#   PDF height is calculated independently for every heatmap and intentionally
#   increases with the number of displayed cluster-gene rows. The unfiltered
#   heatmap can contain >1000 rows and is intended as a technical
#   supplementary/exploratory output rather than a compact figure.
# ==============================================================================

options(stringsAsFactors = FALSE)


# ==============================================================================
# 1. Packages
# ==============================================================================

required_packages <- c(
  "dplyr",
  "tibble",
  "readr",
  "edgeR",
  "ComplexHeatmap",
  "circlize",
  "grid",
  "GSA"
)

missing_packages <- required_packages[
  !vapply(
    required_packages,
    requireNamespace,
    quietly = TRUE,
    FUN.VALUE = logical(1)
  )
]

if (length(missing_packages) > 0L) {
  stop(
    "Missing required packages: ",
    paste(missing_packages, collapse = ", "),
    call. = FALSE
  )
}

suppressPackageStartupMessages({
  library(dplyr)
  library(tibble)
  library(readr)
  library(edgeR)
  library(ComplexHeatmap)
  library(circlize)
  library(grid)
  library(GSA)
})


# ==============================================================================
# 2. Analysis configuration
# ==============================================================================

project_root <- "/home/mateusz/projects/ippas-kunevicius-spatial"
dataset_name <- "maternalFMT_n16samples"

clustering_name <-
  "logNormalizeVstHvg2000_ccaDims20K20PruneSNN0067_leidenRes040"

fdr_threshold <- 0.05
abs_log2fc_threshold <- 0.5

fisher_background_size <- 19437L

zscore_lower_limit <- -2
zscore_upper_limit <- 2

parameter_block <- "FDR005absLog2FC05perCluster"

heatmap_variants <- tibble::tribble(
  ~file_index, ~variant_id, ~max_mean_percent_threshold, ~filter_label,
  1L, "all",      NA_real_, "none",
  2L, "maxPct10", 10,       ">= 10%",
  3L, "maxPct15", 15,       ">= 15%",
  4L, "maxPct20", 20,       ">= 20%",
  5L, "maxPct25", 25,       ">= 25%"
)

chea_library_url <-
  "https://maayanlab.cloud/Enrichr/geneSetLibrary?mode=text&libraryName=ChEA_2022"

chea_clean_names <- c(
  "GR PC12",
  "GR HPC stress",
  "GR HPC",
  "MR HPC",
  "MR HPC stress"
)

chea_full_names <- c(
  "GR PC12 mouse (PMID: 23031785)",
  "GR HPC rat stress (PMID: 34362910)",
  "GR HPC rat (PMID: 34362910)",
  "MR HPC rat (PMID: 34362910)",
  "MR HPC rat stress (PMID: 34362910)"
)

chea_regulator_class <- c(
  "GR",
  "GR",
  "GR",
  "MR",
  "MR"
)

marker_absent_colour <- "grey96"

gr_repetition_colours <- c(
  "0" = marker_absent_colour,
  "1" = "#E1BEE7",
  "2" = "#AB47BC",
  "3" = "#6A1B9A"
)

mr_repetition_colours <- c(
  "0" = marker_absent_colour,
  "1" = "#D1C4E9",
  "2" = "#7E57C2"
)


gr_brain_test <- unique(
  toupper(
    c(
      "FKBP5",
      "HIF3A",
      "DDIT4",
      "TSC22D3",
      "ZBTB16",
      "MAP3K6",
      "MFSD2A",
      "PDK4",
      "PLEKHF1",
      "PLA2G3",
      "PLIN4",
      "KLF15",
      "NFKBIA",
      "SGK1",
      "CDKN1A",
      "MT1M",
      "PER1",
      "ARRDC2",
      "FAM107A",
      "CEBPD",
      "ARL4D",
      "DEPP1",
      "ERRFI1",
      "KLF9",
      "TCIM",
      "FMO2",
      "CASTOR1",
      "TXNIP",
      "SPSB1",
      "PHYHD1",
      "LFNG",
      "SDC4",
      "CCN2",
      "ZNF189",
      "MERTK",
      "GJB6",
      "GALNT15",
      "ZFP36",
      "TINAGL1",
      "TIPARP",
      "LRG1",
      "PMAIP1",
      "UCP2",
      "CABLES1",
      "SERPINE1",
      "ANGPTL4",
      "RHOU",
      "SESN1",
      "NEDD9",
      "DIO2",
      "SMOX",
      "CEBPB",
      "MAFF",
      "XDH",
      "GPD1",
      "TP53INP1",
      "IL6R",
      "TEKT4",
      "TRIB1",
      "HEPH",
      "ACER2",
      "AGT",
      "ADA",
      "BCL6",
      "ADM",
      "MXD4",
      "CSRNP1",
      "LPIN3",
      "PTGDS",
      "MGP",
      "TMEM52",
      "NT5E",
      "CAVIN2",
      "HR",
      "MC4R",
      "FGFRL1",
      "SOX9",
      "DDIT4L",
      "ADAMTS4",
      "RAB7B",
      "KDR",
      "HES5",
      "CXCR4",
      "CDC42EP1",
      "PHLDA1",
      "C2ORF72",
      "NDP",
      "SOX21",
      "EPHB3",
      "SOX2",
      "CREB5",
      "FABP7",
      "TNC",
      "NKX2-2",
      "NES"
    )
  )
)

gr_blood_test <- unique(
  toupper(
    c(
      "FKBP5",
      "TSC22D3",
      "DDIT4",
      "ZBTB16",
      "PER1",
      "TXNIP",
      "SLA",
      "KLF9",
      "DUSP1",
      "PIK3IP1",
      "CD163",
      "SMAP2",
      "NFIL3",
      "GLUL",
      "IL1R2",
      "SESN1",
      "METTL7A",
      "FLT3",
      "SOCS1",
      "SAP30",
      "SPRY1",
      "CLEC4E",
      "IRAK3",
      "SMIM3",
      "ZFP36L2",
      "NFKBIA",
      "FOS",
      "IRS2",
      "CEBPD",
      "IFNGR1",
      "JDP2",
      "RHOB",
      "CPM",
      "IL13RA1",
      "C1QB",
      "TNS1",
      "VSIG4",
      "CXCR4",
      "SLC31A2",
      "CELF2",
      "MERTK",
      "CHKA",
      "IL18RAP",
      "MAP3K6",
      "ARL4A",
      "HERPUD1",
      "THBS1",
      "KLHL24",
      "INSR",
      "BIRC3",
      "TLE1",
      "DAAM2",
      "TUBA4A",
      "GRAMD2B",
      "KLF13",
      "PRDM1",
      "RGS2",
      "SLC19A2",
      "P2RY14",
      "C1QC",
      "ETS2",
      "ALOX5AP",
      "SRGN",
      "AREG",
      "CCND3",
      "MMP19",
      "TP53INP1",
      "TPST1",
      "PIK3R1",
      "RNF144B",
      "SERPINE1",
      "SORT1",
      "IL7R",
      "KIAA0513",
      "KCNJ2",
      "SGK1",
      "SLC1A3",
      "TMOD1",
      "FBXO32",
      "IQGAP2",
      "AKAP13",
      "C1QA",
      "TIPARP",
      "ELL2",
      "RNASE6",
      "GADD45A",
      "LPL",
      "SAMSN1",
      "CSGALNACT1",
      "ABLIM3",
      "FAH",
      "SSH2",
      "HAL",
      "KLF4",
      "TLR2",
      "TSPAN14",
      "CD69",
      "FGD4",
      "FILIP1L",
      "OGFRL1",
      "CRISPLD2",
      "RCAN1",
      "ACSL1",
      "CD55",
      "FRAT1",
      "YPEL5",
      "GYPC",
      "MARVELD1",
      "SH3BP5",
      "SNTB2",
      "FPR1",
      "HPGD",
      "IL18R1",
      "PCTP",
      "RNASE4",
      "ADRB2",
      "HTRA1",
      "SPTLC2",
      "WIPI1",
      "PTEN",
      "LRRC8A",
      "SYTL3",
      "TCN2",
      "GRAMD4",
      "KLF2",
      "TRPM2",
      "ZFP36",
      "ADGRE5",
      "BCAT1",
      "IL6ST",
      "MT1X",
      "SH3PXD2B",
      "TMIGD3",
      "FES",
      "ADM",
      "PLIN2",
      "VCAN",
      "IL10",
      "CEMIP2",
      "YPEL3",
      "CD83",
      "IL1B",
      "LTB",
      "TNF",
      "ATF3",
      "MID1IP1",
      "BCL3",
      "KCNN4",
      "RELB",
      "IFIT3",
      "MEF2C",
      "TRAF1",
      "CYP1B1",
      "IER3",
      "IL1RN",
      "NFKBIE",
      "DUSP6",
      "BHLHE40",
      "SLC2A6",
      "ICAM1",
      "RGS16",
      "SLC15A3",
      "S1PR1",
      "PLAUR",
      "CCL2",
      "PLAU",
      "PTPRE",
      "EGR2",
      "LAT",
      "CD274",
      "ARL4C",
      "CD180",
      "PEA15",
      "IL21R",
      "JUNB",
      "MARCKSL1",
      "ANPEP",
      "CSF2RB",
      "ID3",
      "NFKB2",
      "RGS2",
      "SLC5A3",
      "BCAR3",
      "G0S2",
      "IFIT2",
      "CXCL10",
      "INSIG1",
      "MYC",
      "TNFAIP2",
      "SERPINB2",
      "ARRDC4",
      "CCR7",
      "RSAD2",
      "CKB",
      "GBP1",
      "CX3CR1",
      "NAB2",
      "LCK",
      "BTG2",
      "TLR1",
      "FABP5",
      "XAF1",
      "IER2",
      "MTHFD2",
      "NINJ1",
      "TCF7",
      "CD40",
      "EGR1",
      "OAS3",
      "PPIF",
      "RASGRP1",
      "TRAF3",
      "RNF19B",
      "SOCS3",
      "TASL",
      "TXNRD1",
      "CCND1",
      "CCR1",
      "DTX4",
      "PHLDA1",
      "RASGRP3",
      "SLC7A11",
      "PDE4B",
      "LRP12",
      "MGLL",
      "MYOF"
    )
  )
)

fisher_test_set_order <- c(
  "GR",
  "MR",
  "gr_brain_test",
  "gr_blood_test"
)

# Missing sample-cluster CPM values are retained as NA.
# No imputation is performed.
impute_missing <- FALSE

# Row-clustering parameters.
row_clustering_base_distance <- "2 - r"
row_clustering_r_scale <- 1
row_clustering_same_cluster_bonus <- 0.15
row_clustering_linkage_method <- "complete"

# Exact clustering information shown in the technical heatmap title.
clustering_title <- paste(
  "LogNormalize + VST | HVG = 2000 | CCA dims = 20 |",
  "k = 20 | prune.SNN = 0.0667 | Leiden resolution = 0.40"
)


# ==============================================================================
# 3. Cluster colours and anatomical labels
# ==============================================================================

custom_cluster_colors <- c(
  "1"  = "#e66063",
  "2"  = "#407ba7",
  "3"  = "#31cb00",
  "4"  = "#adb5bd",
  "5"  = "#9e0059",
  "6"  = "#b5838d",
  "7"  = "#002962",
  "8"  = "#004e89",
  "9"  = "#d02224",
  "10" = "#ff9505",
  "11" = "#9c191b",
  "12" = "#e85d04",
  "13" = "#119822",
  "14" = "#6B1E2D",
  "15" = "#ffd100",
  "16" = "#1e441e"
)

custom_cluster_labels <- c(
  "1"  = "posterior & sensory relay thalamic nuclei",
  "2"  = "isocortex, layers 4 & 5",
  "3"  = "cortical layers 1 & hippocampal neuropil",
  "4"  = "Fiber tracts",
  "5"  = "cortical subplate & deep olfactory areas",
  "6"  = "hypothalamus",
  "7"  = "isocortex, layer 6",
  "8"  = "isocortex, layer 2/3",
  "9"  = "reticular, ventral geniculate & habenular region",
  "10" = "striatum-like amygdala nuclei",
  "11" = "medial thalamic nuclei",
  "12" = "caudoputamen",
  "13" = "hippocampal CA fields, pyramidal layer",
  "14" = "meninges & vasculature",
  "15" = "ventricles",
  "16" = "dentate gyrus"
)


# ==============================================================================
# 4. Input and output paths
# ==============================================================================

statistics_dir <- file.path(
  project_root,
  "results",
  dataset_name,
  "pseudobulkPerCluster_geneCounts_edgeR_twoFactorInteraction",
  clustering_name,
  "01_statistics"
)

analysis_prefix <- paste0(
  dataset_name,
  "_",
  clustering_name,
  "_pseudobulkPerCluster_geneCounts_edgeR_twoFactorInteraction"
)

edgeR_results_rdata_file <- file.path(
  statistics_dir,
  "03_edgeRResults",
  paste0(
    analysis_prefix,
    "_edgeRResults.RData"
  )
)

edgeR_model_objects_rdata_file <- file.path(
  statistics_dir,
  "05_objects",
  paste0(
    analysis_prefix,
    "_edgeRModelObjects.RData"
  )
)

heatmap_output_dir <- file.path(
  project_root,
  "results",
  dataset_name,
  "pseudobulkPerCluster_geneCounts_edgeR_twoFactorInteraction",
  clustering_name,
  "02_heatmaps",
  "02_mainEffect_donorGroup",
  "withMRandGRplusBrainBlood"
)

dir.create(
  heatmap_output_dir,
  recursive = TRUE,
  showWarnings = FALSE
)

required_input_files <- c(
  edgeR_results_rdata_file,
  edgeR_model_objects_rdata_file
)

missing_input_files <- required_input_files[
  !file.exists(required_input_files)
]

if (length(missing_input_files) > 0L) {
  stop(
    "Missing required RData file(s):\n",
    paste(missing_input_files, collapse = "\n"),
    call. = FALSE
  )
}


# ==============================================================================
# 5. Output files
# ==============================================================================

results_per_cluster_tsv <- file.path(
  heatmap_output_dir,
  paste0(
    "06_",
    dataset_name,
    "_effectDonorGroup_",
    parameter_block,
    "_maxPctSeries_withMRandGR_resultsPerCluster.tsv"
  )
)

fisher_global_results_tsv <- file.path(
  heatmap_output_dir,
  paste0(
    "07_",
    dataset_name,
    "_effectDonorGroup_",
    parameter_block,
    "_maxPctSeries_4geneSets_FisherEnrichment_global.tsv"
  )
)

fisher_per_cluster_results_tsv <- file.path(
  heatmap_output_dir,
  paste0(
    "08_",
    dataset_name,
    "_effectDonorGroup_",
    parameter_block,
    "_maxPctSeries_4geneSets_FisherEnrichment_perCluster.tsv"
  )
)


# ==============================================================================
# 6. Helper functions
# ==============================================================================

find_donor_group_test_id <- function(test_definitions) {

  required_columns <- c(
    "test_id",
    "sheet_name",
    "comparison"
  )

  missing_columns <- setdiff(
    required_columns,
    colnames(test_definitions)
  )

  if (length(missing_columns) > 0L) {
    stop(
      "Test-definition table is missing: ",
      paste(missing_columns, collapse = ", "),
      call. = FALSE
    )
  }

  test_table <- test_definitions |>
    dplyr::mutate(
      test_id_chr = as.character(.data$test_id),
      sheet_name_chr = as.character(.data$sheet_name),
      comparison_chr = as.character(.data$comparison),
      test_id_lower = tolower(.data$test_id_chr),
      sheet_name_lower = tolower(.data$sheet_name_chr),
      comparison_lower = tolower(.data$comparison_chr)
    )

  # Hard exclusions:
  # donor-group main effect must not be a sex test or interaction test.
  eligible_rows <- test_table |>
    dplyr::filter(
      !grepl("interaction", .data$test_id_lower),
      !grepl("interaction", .data$sheet_name_lower),
      !grepl("sex", .data$test_id_lower),
      !grepl("sex", .data$sheet_name_lower),
      !grepl("male", .data$test_id_lower),
      !grepl("male", .data$sheet_name_lower),
      !grepl("female", .data$test_id_lower),
      !grepl("female", .data$sheet_name_lower),
      !grepl("simple", .data$test_id_lower),
      !grepl("simple", .data$sheet_name_lower)
    )

  # Score only information that is specific enough to identify the main
  # donor-group effect. Importantly, the word "donor" in comparison text alone
  # is NOT sufficient because sex comparisons may contain phrases such as
  # "averaged equally across donor groups".
  scored_rows <- eligible_rows |>
    dplyr::mutate(
      donor_test_score =
        5L * (
          grepl("donor", .data$test_id_lower) |
          grepl("fmt", .data$test_id_lower)
        ) +
        4L * (
          grepl("donor", .data$sheet_name_lower) |
          grepl("fmt", .data$sheet_name_lower)
        ) +
        3L * grepl("group", .data$test_id_lower) +
        2L * grepl("group", .data$sheet_name_lower) +
        3L * (
          grepl("asd", .data$comparison_lower) &
          grepl("neurotypical", .data$comparison_lower)
        ) +
        1L * (
          grepl("asd", .data$test_id_lower) |
          grepl("neurotypical", .data$test_id_lower)
        ) +
        5L * (
          grepl("overall", .data$test_id_lower) |
          grepl("overall", .data$sheet_name_lower)
        )
    ) |>
    dplyr::filter(.data$donor_test_score > 0L)

  if (nrow(scored_rows) == 0L) {
    message("\nAll available edgeR test definitions:")
    print(
      test_definitions |>
        dplyr::select(
          .data$test_id,
          .data$sheet_name,
          .data$comparison
        ),
      n = Inf
    )

    stop(
      "Could not identify any donor-group main-effect candidate.",
      call. = FALSE
    )
  }

  best_score <- max(scored_rows$donor_test_score)

  best_rows <- scored_rows |>
    dplyr::filter(
      .data$donor_test_score == best_score
    )

  if (nrow(best_rows) != 1L) {
    message("\nBest donor-group test candidates:")
    print(
      best_rows |>
        dplyr::select(
          .data$test_id,
          .data$sheet_name,
          .data$comparison,
          .data$donor_test_score
        ),
      n = Inf
    )

    message("\nAll available edgeR test definitions:")
    print(
      test_definitions |>
        dplyr::select(
          .data$test_id,
          .data$sheet_name,
          .data$comparison
        ),
      n = Inf
    )

    stop(
      "Could not uniquely identify the donor-group main-effect test. ",
      "Best-score candidates found: ",
      nrow(best_rows),
      call. = FALSE
    )
  }

  selected_test_id <- as.character(best_rows$test_id[[1]])

  # Final safety check.
  selected_test_id_lower <- tolower(selected_test_id)
  selected_sheet_lower <- tolower(as.character(best_rows$sheet_name[[1]]))

  if (
    grepl("sex", selected_test_id_lower) ||
    grepl("sex", selected_sheet_lower) ||
    grepl("interaction", selected_test_id_lower) ||
    grepl("interaction", selected_sheet_lower)
  ) {
    stop(
      "Internal safety check failed: selected donor-group test appears to be ",
      "a sex or interaction test: ",
      selected_test_id,
      call. = FALSE
    )
  }

  selected_test_id
}


calculate_row_zscores <- function(
  expression_matrix,
  lower_limit = -2,
  upper_limit = 2
) {

  output_matrix <- matrix(
    NA_real_,
    nrow = nrow(expression_matrix),
    ncol = ncol(expression_matrix),
    dimnames = dimnames(expression_matrix)
  )

  for (row_index in seq_len(nrow(expression_matrix))) {

    values <- as.numeric(expression_matrix[row_index, ])
    finite_values <- is.finite(values)

    if (sum(finite_values) < 2L) {
      output_matrix[row_index, finite_values] <- 0
      next
    }

    row_mean <- mean(values[finite_values])
    row_sd <- stats::sd(values[finite_values])

    if (!is.finite(row_sd) || row_sd == 0) {
      output_matrix[row_index, finite_values] <- 0
      next
    }

    output_matrix[row_index, finite_values] <-
      (values[finite_values] - row_mean) / row_sd
  }

  output_matrix[
    is.finite(output_matrix) &
      output_matrix < lower_limit
  ] <- lower_limit

  output_matrix[
    is.finite(output_matrix) &
      output_matrix > upper_limit
  ] <- upper_limit

  output_matrix
}


modified_correlation_distance <- function(
  expression_matrix,
  cluster_labels,
  base_distance = "2 - r",
  r_scale = 1,
  same_cluster_bonus = 0.20
) {

  if (!is.matrix(expression_matrix)) {
    expression_matrix <- as.matrix(expression_matrix)
  }

  if (nrow(expression_matrix) <= 1L) {
    return(
      stats::as.dist(
        matrix(
          0,
          nrow = 1,
          ncol = 1
        )
      )
    )
  }

  cluster_labels <- as.character(cluster_labels)

  if (length(cluster_labels) != nrow(expression_matrix)) {
    stop(
      "The number of cluster labels must equal the number of heatmap rows.",
      call. = FALSE
    )
  }

  if (!is.numeric(r_scale) || length(r_scale) != 1L || !is.finite(r_scale)) {
    stop(
      "`r_scale` must be one finite numeric value.",
      call. = FALSE
    )
  }

  if (
    !is.numeric(same_cluster_bonus) ||
    length(same_cluster_bonus) != 1L ||
    !is.finite(same_cluster_bonus) ||
    same_cluster_bonus < 0 ||
    same_cluster_bonus >= 1
  ) {
    stop(
      "`same_cluster_bonus` must be a finite number in [0, 1).",
      call. = FALSE
    )
  }

  cor_mat <- suppressWarnings(
    stats::cor(
      t(expression_matrix),
      method = "pearson",
      use = "pairwise.complete.obs"
    )
  )

  cor_mat[!is.finite(cor_mat)] <- 0
  diag(cor_mat) <- 1

  base_dist <- if (identical(base_distance, "2 - r")) {
    2 - (cor_mat * r_scale)
  } else if (identical(base_distance, "1 - r")) {
    1 - (cor_mat * r_scale)
  } else {
    stop(
      "`base_distance` must be either '2 - r' or '1 - r'.",
      call. = FALSE
    )
  }

  same_cluster_matrix <- outer(
    cluster_labels,
    cluster_labels,
    FUN = "=="
  )

  dist_mat <- base_dist

  dist_mat[same_cluster_matrix] <-
    base_dist[same_cluster_matrix] * (1 - same_cluster_bonus)

  dist_mat[!same_cluster_matrix] <-
    base_dist[!same_cluster_matrix] * (1 + same_cluster_bonus)

  diag(dist_mat) <- 0
  dist_mat[dist_mat < 0] <- 0

  stats::as.dist(dist_mat)
}


create_modified_row_hclust <- function(
  expression_matrix,
  annotation_table,
  base_distance = "2 - r",
  r_scale = 1,
  same_cluster_bonus = 0.20,
  linkage_method = "complete"
) {

  matched_annotation <- annotation_table[
    match(
      rownames(expression_matrix),
      annotation_table$row_id
    ),
    ,
    drop = FALSE
  ]

  if (
    nrow(matched_annotation) != nrow(expression_matrix) ||
    anyNA(matched_annotation$row_id) ||
    anyNA(matched_annotation$cluster_id)
  ) {
    stop(
      "Failed to match source-cluster annotations to all heatmap rows.",
      call. = FALSE
    )
  }

  modified_distance <- modified_correlation_distance(
    expression_matrix = expression_matrix,
    cluster_labels = matched_annotation$cluster_id,
    base_distance = base_distance,
    r_scale = r_scale,
    same_cluster_bonus = same_cluster_bonus
  )

  stats::hclust(
    modified_distance,
    method = linkage_method
  )
}


format_cluster_label <- function(cluster_id) {
  paste0(
    "C",
    cluster_id,
    " | ",
    unname(custom_cluster_labels[cluster_id])
  )
}


p_value_to_marker <- function(p_value) {

  if (length(p_value) != 1L || is.na(p_value) || !is.finite(p_value)) {
    return("")
  }

  if (p_value < 0.001) {
    return("***")
  }

  if (p_value < 0.01) {
    return("**")
  }

  if (p_value < 0.05) {
    return("*")
  }

  ""
}


format_p_value <- function(p_value) {

  if (length(p_value) != 1L || is.na(p_value) || !is.finite(p_value)) {
    return("NA")
  }

  if (p_value < 0.001) {
    return(
      format(
        p_value,
        scientific = TRUE,
        digits = 3
      )
    )
  }

  formatC(
    p_value,
    format = "f",
    digits = 4
  )
}


run_fisher_target_enrichment <- function(
  foreground_genes,
  target_genes,
  test_set_label,
  background_size = 19437L
) {

  foreground_genes <- unique(
    toupper(
      trimws(
        as.character(
          foreground_genes
        )
      )
    )
  )

  target_genes <- unique(
    toupper(
      trimws(
        as.character(
          target_genes
        )
      )
    )
  )

  foreground_genes <- foreground_genes[
    !is.na(foreground_genes) &
      foreground_genes != ""
  ]

  target_genes <- target_genes[
    !is.na(target_genes) &
      target_genes != ""
  ]

  n_foreground_genes <- length(
    foreground_genes
  )

  n_target_genes <- length(
    target_genes
  )

  overlap_genes <- sort(
    intersect(
      foreground_genes,
      target_genes
    )
  )

  n_overlap_genes <- length(
    overlap_genes
  )

  if (n_foreground_genes > background_size) {
    stop(
      "Foreground contains ",
      n_foreground_genes,
      " unique genes, exceeding Fisher background size ",
      background_size,
      ".",
      call. = FALSE
    )
  }

  if (n_target_genes > background_size) {
    stop(
      test_set_label,
      " target union contains ",
      n_target_genes,
      " genes, exceeding Fisher background size ",
      background_size,
      ".",
      call. = FALSE
    )
  }

  # 2 x 2 contingency table:
  #
  #                         TF target     Not TF target
  #   Foreground                a               b
  #   Background remainder     c               d
  #
  # Total universe is fixed to background_size = 19,437.
  contingency_a <- n_overlap_genes
  contingency_b <- n_foreground_genes - contingency_a
  contingency_c <- n_target_genes - contingency_a
  contingency_d <- background_size -
    contingency_a -
    contingency_b -
    contingency_c

  if (
    contingency_a < 0L ||
    contingency_b < 0L ||
    contingency_c < 0L ||
    contingency_d < 0L
  ) {
    stop(
      "Invalid Fisher contingency table for ",
      test_set_label,
      ": a=",
      contingency_a,
      ", b=",
      contingency_b,
      ", c=",
      contingency_c,
      ", d=",
      contingency_d,
      ", background_size=",
      background_size,
      ".",
      call. = FALSE
    )
  }

  fisher_matrix <- matrix(
    c(
      contingency_a,
      contingency_b,
      contingency_c,
      contingency_d
    ),
    nrow = 2,
    byrow = TRUE,
    dimnames = list(
      set = c(
        "Foreground",
        "Background_remainder"
      ),
      target = c(
        "TF_target",
        "Not_TF_target"
      )
    )
  )

  test_is_defined <-
    n_foreground_genes > 0L &&
    n_target_genes > 0L &&
    (background_size - n_target_genes) > 0L

  if (isTRUE(test_is_defined)) {

    fisher_test <- stats::fisher.test(
      fisher_matrix,
      alternative = "greater"
    )

    p_value <- fisher_test$p.value

    odds_ratio <- if (
      length(fisher_test$estimate) == 1L
    ) {
      as.numeric(
        fisher_test$estimate[[1]]
      )
    } else {
      NA_real_
    }

  } else {

    p_value <- NA_real_
    odds_ratio <- NA_real_
  }

  tibble::tibble(
    test_set = test_set_label,
    background_size = as.integer(
      background_size
    ),
    n_foreground_genes = n_foreground_genes,
    n_test_set_genes = n_target_genes,
    n_overlap_genes = n_overlap_genes,
    odds_ratio = odds_ratio,
    p_value = p_value,
    significance_marker = p_value_to_marker(
      p_value
    ),
    overlap_genes = if (
      n_overlap_genes > 0L
    ) {
      paste(
        overlap_genes,
        collapse = "|"
      )
    } else {
      ""
    }
  )
}


make_repetition_annotation <- function(
  values,
  fill_colours,
  font_size,
  width_mm = 4.5
) {

  values <- as.integer(
    values
  )

  labels <- as.character(
    values
  )

  text_colours <- ifelse(
    values >= max(
      values,
      na.rm = TRUE
    ) &
      values > 1,
    "white",
    "black"
  )

  ComplexHeatmap::AnnotationFunction(
    which = "row",

    width = grid::unit(
      width_mm,
      "mm"
    ),

    var_import = list(
      annotation_values = values,
      annotation_labels = labels,
      annotation_text_colours = text_colours,
      annotation_fill_colours = fill_colours,
      annotation_font_size = font_size
    ),

    fun = function(index) {

      n_current <- length(
        index
      )

      y_positions <- 1 - (
        seq_len(
          n_current
        ) -
          0.5
      ) /
        n_current

      current_values <- annotation_values[
        index
      ]

      current_labels <- annotation_labels[
        index
      ]

      current_text_colours <-
        annotation_text_colours[
          index
        ]

      current_fill <- unname(
        annotation_fill_colours[
          as.character(
            current_values
          )
        ]
      )

      current_fill[
        is.na(
          current_fill
        )
      ] <- marker_absent_colour

      grid::grid.rect(
        x = grid::unit(
          0.5,
          "npc"
        ),

        y = grid::unit(
          y_positions,
          "npc"
        ),

        width = grid::unit(
          1,
          "npc"
        ),

        height = grid::unit(
          1 / n_current,
          "npc"
        ),

        gp = grid::gpar(
          fill = current_fill,
          col = NA
        )
      )

      grid::grid.text(
        label = current_labels,

        x = grid::unit(
          0.5,
          "npc"
        ),

        y = grid::unit(
          y_positions,
          "npc"
        ),

        gp = grid::gpar(
          col = current_text_colours,
          fontsize = annotation_font_size,
          fontface = "bold"
        )
      )
    }
  )
}


load_chea_nervous_nr_sets <- function(
  library_url,
  clean_names,
  full_names,
  regulator_class
) {

  message("\nLoading ChEA 2022 gene-set library:")
  message(library_url)

  chea <- GSA::GSA.read.gmt(
    url(library_url)
  )

  idx_nervous_nr <- which(
    grepl(
      "NR3C1|NR3C2",
      chea$geneset.names,
      ignore.case = TRUE
    ) &
      grepl(
        "HIPPOCAMPUS|STRIATUM|BRAIN|NEUR|PC12",
        chea$geneset.names,
        ignore.case = TRUE
      )
  )

  if (length(idx_nervous_nr) != 5L) {

    message("\nMatched ChEA nervous-system NR3C1/NR3C2 gene sets:")

    if (length(idx_nervous_nr) > 0L) {
      message(
        paste(
          chea$geneset.names[idx_nervous_nr],
          collapse = "\n"
        )
      )
    } else {
      message("<none>")
    }

    stop(
      "Expected exactly 5 nervous-system NR3C1/NR3C2 ChEA gene sets, but found ",
      length(idx_nervous_nr),
      ".",
      call. = FALSE
    )
  }

  chea_nervous_nr <- tibble::tibble(
    original_name = chea$geneset.names[idx_nervous_nr],
    clean_name = clean_names,
    full_name = full_names,
    regulator = regulator_class,
    genes = chea$genesets[idx_nervous_nr]
  )

  chea_nervous_nr <- chea_nervous_nr |>
    dplyr::mutate(
      genes_upper = lapply(
        .data$genes,
        function(x) {
          unique(
            toupper(
              trimws(
                as.character(x)
              )
            )
          )
        }
      )
    )

  message("\nSelected ChEA GR/MR gene sets:")

  print(
    chea_nervous_nr |>
      dplyr::transmute(
        original_name = .data$original_name,
        clean_name = .data$clean_name,
        regulator = .data$regulator,
        n_genes = lengths(.data$genes_upper)
      ),
    n = Inf
  )

  chea_nervous_nr
}


# ==============================================================================
# 7. Load edgeR objects
# ==============================================================================

message("Loading edgeR results RData:")
message(edgeR_results_rdata_file)
load(edgeR_results_rdata_file)

message("\nLoading edgeR model-object RData:")
message(edgeR_model_objects_rdata_file)
load(edgeR_model_objects_rdata_file)

required_objects <- c(
  "edgeR_perCluster_combinedResults",
  "edgeR_perCluster_testDefinitions",
  "edgeR_perCluster_modelObjects"
)

missing_objects <- required_objects[
  !vapply(
    required_objects,
    exists,
    logical(1)
  )
]

if (length(missing_objects) > 0L) {
  stop(
    "Required object(s) missing after loading RData files: ",
    paste(missing_objects, collapse = ", "),
    call. = FALSE
  )
}


# ==============================================================================
# 8. Select FMT donor-group main-effect test
# ==============================================================================

donor_group_test_id <- find_donor_group_test_id(
  edgeR_perCluster_testDefinitions
)

message(
  "\nSelected donor-group test_id: ",
  donor_group_test_id
)

if (!donor_group_test_id %in% names(edgeR_perCluster_combinedResults)) {
  stop(
    "Selected donor-group test is absent from edgeR_perCluster_combinedResults: ",
    donor_group_test_id,
    call. = FALSE
  )
}

donor_group_test_definition <- edgeR_perCluster_testDefinitions |>
  dplyr::filter(
    .data$test_id == donor_group_test_id
  )

if (nrow(donor_group_test_definition) != 1L) {
  stop(
    "Selected donor-group test_id does not map to exactly one test definition: ",
    donor_group_test_id,
    call. = FALSE
  )
}

selected_test_comparison <- as.character(
  donor_group_test_definition$comparison[[1]]
)

selected_test_sheet <- as.character(
  donor_group_test_definition$sheet_name[[1]]
)

message(
  "Selected comparison: ",
  selected_test_comparison
)

message(
  "Selected sheet: ",
  selected_test_sheet
)


# ==============================================================================
# 9. Load ChEA 2022 GR/MR target-gene sets
# ==============================================================================

chea_nervous_nr <- load_chea_nervous_nr_sets(
  library_url = chea_library_url,
  clean_names = chea_clean_names,
  full_names = chea_full_names,
  regulator_class = chea_regulator_class
)


# ==============================================================================
# 10. Select base significant donor-group results
# ==============================================================================

donor_group_results <- edgeR_perCluster_combinedResults[[donor_group_test_id]] |>
  tibble::as_tibble()

required_result_columns <- c(
  "cluster_id",
  "ensembl_gene_id",
  "gene",
  "logFC",
  "PValue",
  "FDR",
  "mean_percent_positive_spots_Neurotypical",
  "mean_percent_positive_spots_ASD"
)

missing_result_columns <- setdiff(
  required_result_columns,
  colnames(donor_group_results)
)

if (length(missing_result_columns) > 0L) {

  percent_related_columns <- grep(
    "percent|positive|spots",
    colnames(donor_group_results),
    ignore.case = TRUE,
    value = TRUE
  )

  message(
    "\nColumns related to percent-positive spots found in the selected table:"
  )

  if (length(percent_related_columns) > 0L) {
    message(
      paste(
        percent_related_columns,
        collapse = "\n"
      )
    )
  } else {
    message("<none>")
  }

  stop(
    "Donor-group results are missing required columns: ",
    paste(
      missing_result_columns,
      collapse = ", "
    ),
    call. = FALSE
  )
}

donor_group_results_annotated <- donor_group_results |>
  dplyr::mutate(
    cluster_id = as.character(
      .data$cluster_id
    ),

    gene_symbol_display = dplyr::if_else(
      is.na(.data$gene) |
        .data$gene == "",
      .data$ensembl_gene_id,
      .data$gene
    ),

    gene_symbol_upper = toupper(
      .data$gene_symbol_display
    ),

    max_mean_percent = pmax(
      .data$mean_percent_positive_spots_Neurotypical,
      .data$mean_percent_positive_spots_ASD,
      na.rm = TRUE
    ),

    max_mean_percent = dplyr::if_else(
      is.infinite(
        .data$max_mean_percent
      ),
      NA_real_,
      .data$max_mean_percent
    )
  )

significant_donor_group_base <- donor_group_results_annotated |>
  dplyr::filter(
    !is.na(.data$FDR),
    !is.na(.data$logFC),
    .data$FDR < fdr_threshold,
    abs(.data$logFC) >= abs_log2fc_threshold
  ) |>
  dplyr::mutate(
    abs_logFC = abs(.data$logFC),

    effect_direction = dplyr::case_when(
      .data$logFC > 0 ~ "UP",
      .data$logFC < 0 ~ "DOWN",
      TRUE ~ "ZERO"
    ),

    fdr_symbol = dplyr::case_when(
      .data$FDR < 0.001 ~ "***",
      .data$FDR < 0.01 ~ "**",
      .data$FDR < 0.05 ~ "*",
      TRUE ~ ""
    ),

    log2fc_symbol = dplyr::case_when(
      .data$abs_logFC >= 1.0 ~ "###",
      .data$abs_logFC >= 0.8 ~ "##",
      .data$abs_logFC >= 0.5 ~ "#",
      TRUE ~ ""
    )
  ) |>
  dplyr::arrange(
    as.integer(.data$cluster_id),
    .data$FDR,
    dplyr::desc(.data$abs_logFC)
  )

for (set_index in seq_len(nrow(chea_nervous_nr))) {

  set_column_name <- chea_nervous_nr$clean_name[[set_index]]
  set_genes_upper <- chea_nervous_nr$genes_upper[[set_index]]

  significant_donor_group_base[[set_column_name]] <- as.integer(
    significant_donor_group_base$gene_symbol_upper %in% set_genes_upper
  )
}

gr_set_names <- chea_nervous_nr$clean_name[
  chea_nervous_nr$regulator == "GR"
]

mr_set_names <- chea_nervous_nr$clean_name[
  chea_nervous_nr$regulator == "MR"
]

if (length(gr_set_names) != 3L) {
  stop(
    "Expected exactly 3 GR ChEA sets, but found ",
    length(gr_set_names),
    ".",
    call. = FALSE
  )
}

if (length(mr_set_names) != 2L) {
  stop(
    "Expected exactly 2 MR ChEA sets, but found ",
    length(mr_set_names),
    ".",
    call. = FALSE
  )
}

significant_donor_group_base$GR_repetition <- rowSums(
  as.matrix(
    significant_donor_group_base[
      ,
      gr_set_names,
      drop = FALSE
    ]
  )
)

significant_donor_group_base$MR_repetition <- rowSums(
  as.matrix(
    significant_donor_group_base[
      ,
      mr_set_names,
      drop = FALSE
    ]
  )
)

gr_target_union <- unique(
  unlist(
    chea_nervous_nr$genes_upper[
      chea_nervous_nr$regulator == "GR"
    ],
    use.names = FALSE
  )
)

mr_target_union <- unique(
  unlist(
    chea_nervous_nr$genes_upper[
      chea_nervous_nr$regulator == "MR"
    ],
    use.names = FALSE
  )
)


fisher_test_sets <- list(
  GR = gr_target_union,
  MR = mr_target_union,
  gr_brain_test = gr_brain_test,
  gr_blood_test = gr_blood_test
)

if (!identical(
  names(fisher_test_sets),
  fisher_test_set_order
)) {
  stop(
    "Internal Fisher test-set order mismatch.",
    call. = FALSE
  )
}

message("\nFisher test-set sizes:")

print(
  tibble::tibble(
    test_set = names(
      fisher_test_sets
    ),
    n_genes = lengths(
      fisher_test_sets
    )
  ),
  n = Inf
)

if (nrow(significant_donor_group_base) == 0L) {
  stop(
    "No donor-group result satisfies FDR < ",
    fdr_threshold,
    " and abs(log2FC) >= ",
    abs_log2fc_threshold,
    ".",
    call. = FALSE
  )
}

base_significant_clusters <- sort(
  unique(
    as.integer(
      significant_donor_group_base$cluster_id
    )
  )
)

base_significant_cluster_ids <- as.character(
  base_significant_clusters
)

missing_model_clusters <- setdiff(
  base_significant_cluster_ids,
  names(edgeR_perCluster_modelObjects)
)

if (length(missing_model_clusters) > 0L) {
  stop(
    "Model RData is missing significant cluster(s): ",
    paste(
      missing_model_clusters,
      collapse = ", "
    ),
    call. = FALSE
  )
}

message(
  "\nBase significant cluster-gene results: ",
  nrow(significant_donor_group_base)
)

message(
  "Base unique genes: ",
  length(
    unique(
      significant_donor_group_base$ensembl_gene_id
    )
  )
)

message(
  "Base significant clusters: ",
  paste(
    base_significant_cluster_ids,
    collapse = ", "
  )
)


# ==============================================================================
# 11. Extract sample metadata from cluster DGEList objects
# ==============================================================================

sample_metadata_list <- lapply(
  base_significant_cluster_ids,
  function(cluster_id_current) {

    model_object <- edgeR_perCluster_modelObjects[[cluster_id_current]]

    if (is.null(model_object$dge)) {
      stop(
        "DGEList is missing for cluster ",
        cluster_id_current,
        call. = FALSE
      )
    }

    dge_samples <- model_object$dge$samples |>
      tibble::rownames_to_column("dge_rowname") |>
      tibble::as_tibble()

    required_dge_sample_columns <- c(
      "sample_ID",
      "fmt_donor_group",
      "sex"
    )

    missing_dge_sample_columns <- setdiff(
      required_dge_sample_columns,
      colnames(dge_samples)
    )

    if (length(missing_dge_sample_columns) > 0L) {
      stop(
        "DGEList sample metadata for cluster ",
        cluster_id_current,
        " is missing: ",
        paste(
          missing_dge_sample_columns,
          collapse = ", "
        ),
        call. = FALSE
      )
    }

    dge_samples |>
      dplyr::transmute(
        sample_ID = as.character(.data$sample_ID),
        fmt_donor_group = as.character(.data$fmt_donor_group),
        sex = as.character(.data$sex)
      )
  }
)

sample_metadata <- sample_metadata_list |>
  dplyr::bind_rows() |>
  dplyr::distinct(
    .data$sample_ID,
    .data$fmt_donor_group,
    .data$sex
  )

metadata_conflicts <- sample_metadata |>
  dplyr::count(
    .data$sample_ID,
    name = "n_metadata_rows"
  ) |>
  dplyr::filter(
    .data$n_metadata_rows > 1L
  )

if (nrow(metadata_conflicts) > 0L) {
  stop(
    "Conflicting Sex/Group metadata found for sample(s): ",
    paste(
      metadata_conflicts$sample_ID,
      collapse = ", "
    ),
    call. = FALSE
  )
}

sample_metadata <- sample_metadata |>
  dplyr::mutate(
    sex = factor(
      .data$sex,
      levels = c(
        "Male",
        "Female"
      )
    ),

    fmt_donor_group = factor(
      .data$fmt_donor_group,
      levels = c(
        "Neurotypical",
        "ASD"
      )
    )
  )

if (anyNA(sample_metadata$sex)) {
  stop(
    "Unexpected sex value in DGEList metadata.",
    call. = FALSE
  )
}

if (anyNA(sample_metadata$fmt_donor_group)) {
  stop(
    "Unexpected fmt_donor_group value in DGEList metadata.",
    call. = FALSE
  )
}

sample_metadata <- sample_metadata |>
  dplyr::arrange(
    .data$sex,
    .data$fmt_donor_group,
    .data$sample_ID
  ) |>
  dplyr::mutate(
    sample_order = dplyr::row_number(),

    combined_group = factor(
      paste(
        as.character(.data$sex),
        as.character(.data$fmt_donor_group),
        sep = "_"
      ),
      levels = c(
        "Male_Neurotypical",
        "Male_ASD",
        "Female_Neurotypical",
        "Female_ASD"
      )
    )
  )

sample_order <- as.character(
  sample_metadata$sample_ID
)

message("\nSample order used in all heatmaps:")

print(
  sample_metadata |>
    dplyr::select(
      .data$sample_order,
      .data$sample_ID,
      .data$sex,
      .data$fmt_donor_group,
      .data$combined_group
    ),
  n = Inf
)


# ==============================================================================
# 12. Calculate sample-level TMM-normalized CPM
# ==============================================================================

cluster_cpm_matrices <- lapply(
  base_significant_cluster_ids,
  function(cluster_id_current) {

    dge <- edgeR_perCluster_modelObjects[[cluster_id_current]]$dge

    cpm_matrix <- edgeR::cpm(
      dge,
      normalized.lib.sizes = TRUE,
      log = FALSE
    )

    if (is.null(rownames(cpm_matrix))) {
      stop(
        "TMM-CPM matrix has no gene IDs for cluster ",
        cluster_id_current,
        call. = FALSE
      )
    }

    if (is.null(colnames(cpm_matrix))) {
      stop(
        "TMM-CPM matrix has no sample IDs for cluster ",
        cluster_id_current,
        call. = FALSE
      )
    }

    cpm_matrix
  }
)

names(cluster_cpm_matrices) <- base_significant_cluster_ids


# ==============================================================================
# 13. Build base cluster-gene x sample CPM matrix
# ==============================================================================

base_row_ids <- paste0(
  ifelse(
    is.na(significant_donor_group_base$gene) |
      significant_donor_group_base$gene == "",
    significant_donor_group_base$ensembl_gene_id,
    significant_donor_group_base$gene
  ),
  " [C",
  significant_donor_group_base$cluster_id,
  "]"
)

if (anyDuplicated(base_row_ids) > 0L) {

  duplicated_labels <- unique(
    base_row_ids[
      duplicated(base_row_ids)
    ]
  )

  stop(
    "Duplicated gene-cluster row labels detected: ",
    paste(
      duplicated_labels,
      collapse = ", "
    ),
    call. = FALSE
  )
}

significant_donor_group_base <- significant_donor_group_base |>
  dplyr::mutate(
    row_id = base_row_ids
  )

sample_level_cpm_matrix_base <- matrix(
  NA_real_,
  nrow = nrow(significant_donor_group_base),
  ncol = length(sample_order),
  dimnames = list(
    base_row_ids,
    sample_order
  )
)

for (row_index in seq_len(nrow(significant_donor_group_base))) {

  current_cluster <- significant_donor_group_base$cluster_id[[row_index]]
  current_gene_id <- significant_donor_group_base$ensembl_gene_id[[row_index]]
  current_cpm_matrix <- cluster_cpm_matrices[[current_cluster]]

  gene_match <- match(
    current_gene_id,
    rownames(current_cpm_matrix)
  )

  if (is.na(gene_match)) {
    stop(
      "Gene ",
      current_gene_id,
      " is missing from the tested DGEList genes for cluster ",
      current_cluster,
      call. = FALSE
    )
  }

  available_samples <- intersect(
    sample_order,
    colnames(current_cpm_matrix)
  )

  sample_level_cpm_matrix_base[
    row_index,
    available_samples
  ] <- current_cpm_matrix[
    gene_match,
    available_samples,
    drop = TRUE
  ]
}

if (all(is.na(sample_level_cpm_matrix_base))) {
  stop(
    "The complete base cluster-gene CPM matrix contains only NA values.",
    call. = FALSE
  )
}

message(
  "\nBase missing sample-cluster CPM values retained as NA: ",
  sum(
    is.na(
      sample_level_cpm_matrix_base
    )
  )
)


# ==============================================================================
# 14. Common heatmap colours
# ==============================================================================

heatmap_color_function <- circlize::colorRamp2(
  c(
    -2,
    0,
    2
  ),
  c(
    "#2166AC",
    "white",
    "#B2182B"
  )
)

max_mean_percent_color_function <- circlize::colorRamp2(
  c(
    0,
    25,
    50,
    75,
    100
  ),
  c(
    "#F3E8FF",
    "#DDD6FE",
    "#C084FC",
    "#9333EA",
    "#4C1D95"
  )
)

sex_colors <- c(
  "Male" = "#3C78D8",
  "Female" = "#C050A0"
)

group_colors <- c(
  "Neurotypical" = "grey70",
  "ASD" = "black"
)


# ==============================================================================
# 15. Helper functions for heatmap annotations and legends
# ==============================================================================

make_top_annotation <- function() {

  ComplexHeatmap::HeatmapAnnotation(
    Group = sample_metadata$fmt_donor_group,
    Sex = sample_metadata$sex,

    col = list(
      Group = group_colors,
      Sex = sex_colors
    ),

    simple_anno_size = grid::unit(
      3.0,
      "mm"
    ),

    annotation_name_side = "left",

    annotation_name_gp = grid::gpar(
      fontsize = 9,
      fontface = "bold"
    ),

    annotation_legend_param = list(
      Group = list(
        title = "FMT donor group",
        ncol = 1
      ),
      Sex = list(
        title = "Sex",
        ncol = 1
      )
    )
  )
}


make_gr_repetition_legend <- function(
  fisher_marker = ""
) {

  legend_title <- if (
    fisher_marker == ""
  ) {
    "GR target repetition"
  } else {
    paste0(
      "GR target repetition ",
      fisher_marker
    )
  }

  ComplexHeatmap::Legend(
    title = legend_title,

    at = c(
      "0",
      "1",
      "2",
      "3"
    ),

    labels = c(
      "0 = absent",
      "1 = 1/3 ChEA sets",
      "2 = 2/3 ChEA sets",
      "3 = 3/3 ChEA sets"
    ),

    legend_gp = grid::gpar(
      fill = unname(
        gr_repetition_colours[
          c(
            "0",
            "1",
            "2",
            "3"
          )
        ]
      ),
      col = NA
    ),

    title_gp = grid::gpar(
      fontsize = 9,
      fontface = "bold"
    ),

    labels_gp = grid::gpar(
      fontsize = 8
    )
  )
}


make_mr_repetition_legend <- function(
  fisher_marker = ""
) {

  legend_title <- if (
    fisher_marker == ""
  ) {
    "MR target repetition"
  } else {
    paste0(
      "MR target repetition ",
      fisher_marker
    )
  }

  ComplexHeatmap::Legend(
    title = legend_title,

    at = c(
      "0",
      "1",
      "2"
    ),

    labels = c(
      "0 = absent",
      "1 = 1/2 ChEA sets",
      "2 = 2/2 ChEA sets"
    ),

    legend_gp = grid::gpar(
      fill = unname(
        mr_repetition_colours[
          c(
            "0",
            "1",
            "2"
          )
        ]
      ),
      col = NA
    ),

    title_gp = grid::gpar(
      fontsize = 9,
      fontface = "bold"
    ),

    labels_gp = grid::gpar(
      fontsize = 8
    )
  )
}


make_fdr_marker_legend <- function() {

  ComplexHeatmap::Legend(
    title = "FDR marker",

    labels = c(
      "FDR < 0.05",
      "FDR < 0.01",
      "FDR < 0.001"
    ),

    graphics = list(
      function(x, y, w, h) {
        grid::grid.text(
          "*",
          x = x,
          y = y,
          gp = grid::gpar(
            fontsize = 10,
            fontface = "bold"
          )
        )
      },

      function(x, y, w, h) {
        grid::grid.text(
          "**",
          x = x,
          y = y,
          gp = grid::gpar(
            fontsize = 10,
            fontface = "bold"
          )
        )
      },

      function(x, y, w, h) {
        grid::grid.text(
          "***",
          x = x,
          y = y,
          gp = grid::gpar(
            fontsize = 10,
            fontface = "bold"
          )
        )
      }
    ),

    grid_width = grid::unit(
      7,
      "mm"
    ),

    grid_height = grid::unit(
      4,
      "mm"
    ),

    title_gp = grid::gpar(
      fontsize = 9,
      fontface = "bold"
    ),

    labels_gp = grid::gpar(
      fontsize = 8
    )
  )
}


make_log2fc_marker_legend <- function() {

  ComplexHeatmap::Legend(
    title = "|log2FC| marker",

    labels = c(
      "0.5 <= |log2FC| < 0.8",
      "0.8 <= |log2FC| < 1.0",
      "|log2FC| >= 1.0"
    ),

    graphics = list(
      function(x, y, w, h) {
        grid::grid.text(
          "#",
          x = x,
          y = y,
          gp = grid::gpar(
            fontsize = 10,
            fontface = "bold"
          )
        )
      },

      function(x, y, w, h) {
        grid::grid.text(
          "##",
          x = x,
          y = y,
          gp = grid::gpar(
            fontsize = 10,
            fontface = "bold"
          )
        )
      },

      function(x, y, w, h) {
        grid::grid.text(
          "###",
          x = x,
          y = y,
          gp = grid::gpar(
            fontsize = 10,
            fontface = "bold"
          )
        )
      }
    ),

    grid_width = grid::unit(
      9,
      "mm"
    ),

    grid_height = grid::unit(
      4,
      "mm"
    ),

    title_gp = grid::gpar(
      fontsize = 9,
      fontface = "bold"
    ),

    labels_gp = grid::gpar(
      fontsize = 8
    )
  )
}


# ==============================================================================
# 16. Function generating one heatmap variant
# ==============================================================================

generate_heatmap_variant <- function(
  file_index,
  variant_id,
  max_mean_percent_threshold,
  filter_label
) {

  message("\n")
  message(
    paste(
      rep(
        "=",
        78
      ),
      collapse = ""
    )
  )

  message(
    "Generating heatmap variant: ",
    variant_id
  )

  message(
    "Max mean % filter: ",
    filter_label
  )

  if (is.na(max_mean_percent_threshold)) {

    significant_current <- significant_donor_group_base

  } else {

    significant_current <- significant_donor_group_base |>
      dplyr::filter(
        !is.na(.data$max_mean_percent),
        .data$max_mean_percent >= max_mean_percent_threshold
      )
  }

  if (nrow(significant_current) == 0L) {
    stop(
      "Heatmap variant '",
      variant_id,
      "' contains zero rows after applying Max mean % filter ",
      filter_label,
      ".",
      call. = FALSE
    )
  }

  fisher_foreground_genes <- unique(
    significant_current$gene_symbol_upper
  )

  fisher_global_current <- dplyr::bind_rows(
    lapply(
      fisher_test_set_order,
      function(test_set_current) {

        run_fisher_target_enrichment(
          foreground_genes = fisher_foreground_genes,
          target_genes = fisher_test_sets[[test_set_current]],
          test_set_label = test_set_current,
          background_size = fisher_background_size
        )
      }
    )
  ) |>
    dplyr::mutate(
      variant_order = file_index,
      variant_id = variant_id,
      max_mean_percent_threshold = max_mean_percent_threshold,
      max_mean_percent_filter = filter_label,
      cluster_id = NA_integer_,
      anatomical_region = NA_character_,
      .before = 1
    )

  gr_fisher <- fisher_global_current |>
    dplyr::filter(
      .data$test_set == "GR"
    )

  mr_fisher <- fisher_global_current |>
    dplyr::filter(
      .data$test_set == "MR"
    )

  if (
    nrow(gr_fisher) != 1L ||
    nrow(mr_fisher) != 1L
  ) {
    stop(
      "Could not uniquely retrieve global GR/MR Fisher results.",
      call. = FALSE
    )
  }

  gr_fisher_p <- gr_fisher$p_value[[1]]
  mr_fisher_p <- mr_fisher$p_value[[1]]

  gr_fisher_marker <- gr_fisher$significance_marker[[1]]
  mr_fisher_marker <- mr_fisher$significance_marker[[1]]

  all_cluster_ids_for_fisher <- names(
    custom_cluster_labels
  )

  fisher_per_cluster_current <- dplyr::bind_rows(
    lapply(
      all_cluster_ids_for_fisher,
      function(cluster_id_current) {

        cluster_foreground_genes <- unique(
          significant_current$gene_symbol_upper[
            significant_current$cluster_id == cluster_id_current
          ]
        )

        dplyr::bind_rows(
          lapply(
            fisher_test_set_order,
            function(test_set_current) {

              run_fisher_target_enrichment(
                foreground_genes = cluster_foreground_genes,
                target_genes = fisher_test_sets[[test_set_current]],
                test_set_label = test_set_current,
                background_size = fisher_background_size
              )
            }
          )
        ) |>
          dplyr::mutate(
            variant_order = file_index,
            variant_id = variant_id,
            max_mean_percent_threshold = max_mean_percent_threshold,
            max_mean_percent_filter = filter_label,
            cluster_id = as.integer(
              cluster_id_current
            ),
            anatomical_region = unname(
              custom_cluster_labels[
                cluster_id_current
              ]
            ),
            .before = 1
          )
      }
    )
  ) |>
    dplyr::group_by(
      .data$variant_id
    ) |>
    dplyr::mutate(
      FDR_BH = stats::p.adjust(
        .data$p_value,
        method = "BH"
      ),

      FDR_significance_marker = dplyr::case_when(
        !is.na(.data$FDR_BH) &
          .data$FDR_BH < 0.001 ~ "***",
        !is.na(.data$FDR_BH) &
          .data$FDR_BH < 0.01 ~ "**",
        !is.na(.data$FDR_BH) &
          .data$FDR_BH < 0.05 ~ "*",
        TRUE ~ ""
      )
    ) |>
    dplyr::ungroup() |>
    dplyr::select(
      .data$variant_order,
      .data$variant_id,
      .data$max_mean_percent_threshold,
      .data$max_mean_percent_filter,
      .data$cluster_id,
      .data$anatomical_region,
      .data$test_set,
      .data$background_size,
      .data$n_foreground_genes,
      .data$n_test_set_genes,
      .data$n_overlap_genes,
      .data$odds_ratio,
      .data$p_value,
      .data$significance_marker,
      .data$FDR_BH,
      .data$FDR_significance_marker,
      .data$overlap_genes
    )

  # Recalculate the number of clusters containing each gene specifically
  # for the currently displayed heatmap.
  significant_current <- significant_current |>
    dplyr::group_by(.data$ensembl_gene_id) |>
    dplyr::mutate(
      n_clusters_for_gene = dplyr::n_distinct(.data$cluster_id)
    ) |>
    dplyr::ungroup()

  current_row_ids <- significant_current$row_id

  sample_level_cpm_matrix_current <- sample_level_cpm_matrix_base[
    current_row_ids,
    ,
    drop = FALSE
  ]

  number_missing_values <- sum(
    is.na(
      sample_level_cpm_matrix_current
    )
  )

  log2_cpm_matrix_current <- log2(
    sample_level_cpm_matrix_current + 1
  )

  # Row-wise Z-scores are recalculated independently for every variant.
  zscore_matrix_current <- calculate_row_zscores(
    expression_matrix = log2_cpm_matrix_current,
    lower_limit = zscore_lower_limit,
    upper_limit = zscore_upper_limit
  )

  row_annotation_table <- significant_current |>
    dplyr::transmute(
      row_id = .data$row_id,
      cluster_id = .data$cluster_id,

      cluster_label = vapply(
        .data$cluster_id,
        format_cluster_label,
        FUN.VALUE = character(1)
      ),

      logFC = .data$logFC,
      abs_logFC = .data$abs_logFC,
      PValue = .data$PValue,
      FDR = .data$FDR,
      max_mean_percent = .data$max_mean_percent,
      fdr_symbol = .data$fdr_symbol,
      log2fc_symbol = .data$log2fc_symbol,
      n_clusters_for_gene = .data$n_clusters_for_gene
    )

  # Recalculate clustering independently for the current filtered heatmap.
  if (nrow(zscore_matrix_current) > 1L) {

    hc_rows <- create_modified_row_hclust(
      expression_matrix = zscore_matrix_current,
      annotation_table = row_annotation_table,
      base_distance = row_clustering_base_distance,
      r_scale = row_clustering_r_scale,
      same_cluster_bonus = row_clustering_same_cluster_bonus,
      linkage_method = row_clustering_linkage_method
    )

    cluster_rows_current <- hc_rows
    row_dend_reorder_current <- row_annotation_table$logFC

  } else {

    cluster_rows_current <- FALSE
    row_dend_reorder_current <- FALSE
  }

  cluster_factor_levels <- as.character(
    sort(
      unique(
        as.integer(
          row_annotation_table$cluster_id
        )
      )
    )
  )

  cluster_annotation_colors <- custom_cluster_colors[
    cluster_factor_levels
  ]

  names(
    cluster_annotation_colors
  ) <- cluster_factor_levels

  # Number of displayed cluster-gene results per cluster in this exact variant.
  cluster_result_counts <- table(
    factor(
      row_annotation_table$cluster_id,
      levels = cluster_factor_levels
    )
  )

  cluster_legend_labels <- paste0(
    "C",
    cluster_factor_levels,
    " (n = ",
    as.integer(cluster_result_counts),
    "): ",
    unname(
      custom_cluster_labels[
        cluster_factor_levels
      ]
    )
  )

  number_of_results <- nrow(
    significant_current
  )

  number_of_unique_genes <- length(
    unique(
      significant_current$ensembl_gene_id
    )
  )

  number_of_clusters <- length(
    cluster_factor_levels
  )

  number_of_samples <- ncol(
    zscore_matrix_current
  )

  annotation_row_font_size <- if (number_of_results <= 100L) {
    7.0
  } else if (number_of_results <= 300L) {
    5.6
  } else if (number_of_results <= 700L) {
    4.4
  } else {
    3.6
  }

  percent_annotation_labels <- ifelse(
    is.na(
      row_annotation_table$max_mean_percent
    ),
    "NA",
    paste0(
      round(
        row_annotation_table$max_mean_percent
      ),
      "%"
    )
  )

  percent_annotation_text_colour <- ifelse(
    !is.na(
      row_annotation_table$max_mean_percent
    ) &
      row_annotation_table$max_mean_percent > 70,
    "white",
    "black"
  )

  max_mean_percent_annotation <- ComplexHeatmap::AnnotationFunction(
    which = "row",

    width = grid::unit(
      5.5,
      "mm"
    ),

    var_import = list(
      values = row_annotation_table$max_mean_percent,
      labels = percent_annotation_labels,
      text_colours = percent_annotation_text_colour,
      colour_function = max_mean_percent_color_function,
      font_size = annotation_row_font_size
    ),

    fun = function(index) {

      n_current <- length(index)

      y_positions <- 1 - (
        seq_len(n_current) - 0.5
      ) / n_current

      current_values <- values[index]
      current_labels <- labels[index]
      current_text_colours <- text_colours[index]

      current_fill <- rep(
        "grey90",
        n_current
      )

      finite_values <- is.finite(
        current_values
      )

      current_fill[finite_values] <- colour_function(
        current_values[finite_values]
      )

      grid::grid.rect(
        x = grid::unit(
          0.5,
          "npc"
        ),

        y = grid::unit(
          y_positions,
          "npc"
        ),

        width = grid::unit(
          1,
          "npc"
        ),

        height = grid::unit(
          1 / n_current,
          "npc"
        ),

        gp = grid::gpar(
          fill = current_fill,
          col = NA
        )
      )

      grid::grid.text(
        label = current_labels,

        x = grid::unit(
          0.5,
          "npc"
        ),

        y = grid::unit(
          y_positions,
          "npc"
        ),

        gp = grid::gpar(
          col = current_text_colours,
          fontsize = font_size,
          fontface = "bold"
        )
      )
    }
  )

  gene_symbol_annotation_width <-
    ComplexHeatmap::max_text_width(
      current_row_ids,
      gp = grid::gpar(
        fontsize = annotation_row_font_size
      )
    ) +
    grid::unit(
      1.5,
      "mm"
    )

  gr_repetition_annotation <- make_repetition_annotation(
    values = significant_current$GR_repetition,
    fill_colours = gr_repetition_colours,
    font_size = annotation_row_font_size,
    width_mm = 4.5
  )

  mr_repetition_annotation <- make_repetition_annotation(
    values = significant_current$MR_repetition,
    fill_colours = mr_repetition_colours,
    font_size = annotation_row_font_size,
    width_mm = 4.5
  )

  gr_annotation_label <- if (
    gr_fisher_marker == ""
  ) {
    "GR"
  } else {
    paste0(
      "GR ",
      gr_fisher_marker
    )
  }

  mr_annotation_label <- if (
    mr_fisher_marker == ""
  ) {
    "MR"
  } else {
    paste0(
      "MR ",
      mr_fisher_marker
    )
  }

  right_annotation <- ComplexHeatmap::rowAnnotation(
    GR = gr_repetition_annotation,
    MR = mr_repetition_annotation,

    Cluster = row_annotation_table$cluster_id,

    `Max mean %` = max_mean_percent_annotation,

    `FDR marker` = ComplexHeatmap::anno_text(
      row_annotation_table$fdr_symbol,

      location = grid::unit(
        0.5,
        "npc"
      ),

      just = "center",

      gp = grid::gpar(
        col = "black",
        fontsize = annotation_row_font_size,
        fontface = "bold"
      ),

      width = grid::unit(
        3.5,
        "mm"
      )
    ),

    `|log2FC| marker` = ComplexHeatmap::anno_text(
      row_annotation_table$log2fc_symbol,

      location = grid::unit(
        0.5,
        "npc"
      ),

      just = "center",

      gp = grid::gpar(
        col = "black",
        fontsize = annotation_row_font_size,
        fontface = "bold"
      ),

      width = grid::unit(
        4.5,
        "mm"
      )
    ),

    `n clusters` = ComplexHeatmap::anno_text(
      as.character(
        row_annotation_table$n_clusters_for_gene
      ),

      location = grid::unit(
        0.5,
        "npc"
      ),

      just = "center",

      gp = grid::gpar(
        col = "black",
        fontsize = annotation_row_font_size,
        fontface = "bold"
      ),

      width = grid::unit(
        4.0,
        "mm"
      )
    ),

    `Gene symbol` = ComplexHeatmap::anno_text(
      current_row_ids,

      location = grid::unit(
        0,
        "npc"
      ),

      just = "left",

      gp = grid::gpar(
        col = "black",
        fontsize = annotation_row_font_size
      ),

      width = gene_symbol_annotation_width
    ),

    col = list(
      Cluster = cluster_annotation_colors
    ),

    simple_anno_size = grid::unit(
      4.2,
      "mm"
    ),

    # Single scalar gap is intentionally used here.
    # ComplexHeatmap applies it uniformly between all row annotations, so the
    # code remains valid if GR/MR or other annotation columns are added/removed.
    gap = grid::unit(
      0.60,
      "mm"
    ),

    show_annotation_name = c(
      GR = TRUE,
      MR = TRUE,
      Cluster = TRUE,
      `Max mean %` = TRUE,
      `FDR marker` = TRUE,
      `|log2FC| marker` = TRUE,
      `n clusters` = TRUE,
      `Gene symbol` = TRUE
    ),

    annotation_label = c(
      GR = gr_annotation_label,
      MR = mr_annotation_label,
      Cluster = "Cluster",
      `Max mean %` = "Max mean %",
      `FDR marker` = "FDR marker",
      `|log2FC| marker` = "|log2FC| marker",
      `n clusters` = "n clusters",
      `Gene symbol` = "Gene symbol"
    ),

    annotation_name_side = "top",

    annotation_name_rot = c(
      GR = 45,
      MR = 45,
      Cluster = 45,
      `Max mean %` = 45,
      `FDR marker` = 45,
      `|log2FC| marker` = 45,
      `n clusters` = 45,
      `Gene symbol` = 45
    ),

    annotation_name_gp = grid::gpar(
      fontsize = 8,
      fontface = "bold"
    ),

    annotation_legend_param = list(
      Cluster = list(
        title = "Source cluster",
        labels = cluster_legend_labels,
        at = cluster_factor_levels,
        ncol = 1
      )
    )
  )

  top_annotation <- make_top_annotation()

  heatmap_title_lines <- c(
    "FMT donor-group main effect: significant genes per cluster",

    paste0(
      "Test: ",
      selected_test_comparison,
      " | test_id = ",
      donor_group_test_id
    ),

    paste0(
      "Selection: FDR < ",
      fdr_threshold,
      " and |log2FC| >= ",
      abs_log2fc_threshold,
      " | Max mean % filter: ",
      filter_label,
      " | ",
      number_of_results,
      " cluster-gene results | ",
      number_of_unique_genes,
      " unique genes | ",
      number_of_clusters,
      " clusters"
    ),

    "Input: sample-level TMM-normalized CPM from each cluster DGEList",

    paste0(
      "Transformation: log2(CPM + 1) -> row Z-score clipped to [",
      zscore_lower_limit,
      ", ",
      zscore_upper_limit,
      "]"
    ),

    paste0(
      "Missing sample-cluster CPM retained as NA (shown in grey)",
      " | missing values: ",
      number_missing_values
    ),

    paste0(
      "Columns: Male Neurotypical -> Male ASD -> Female Neurotypical -> Female ASD",
      " | ",
      number_of_samples,
      " samples"
    ),

    paste0(
      "Row annotations: Cluster = source Leiden cluster",
      " | Max mean % = maximum mean positive spots across Neurotypical and ASD donor groups"
    ),

    paste0(
      "ChEA 2022 target repetition: GR = sum across 3 GR sets (0-3)",
      " | MR = sum across 2 MR sets (0-2)"
    ),

    paste0(
      "Additional Fisher-only gene sets: gr_brain_test (n = ",
      length(
        gr_brain_test
      ),
      ") | gr_blood_test (n = ",
      length(
        gr_blood_test
      ),
      ")"
    ),

    paste0(
      "One-sided Fisher enrichment (alternative = greater; fixed background N = ",
      format(
        fisher_background_size,
        big.mark = ","
      ),
      "):",
      " GR p = ",
      format_p_value(
        gr_fisher_p
      ),
      ifelse(
        gr_fisher_marker == "",
        "",
        paste0(
          " ",
          gr_fisher_marker
        )
      ),
      " | MR p = ",
      format_p_value(
        mr_fisher_p
      ),
      ifelse(
        mr_fisher_marker == "",
        "",
        paste0(
          " ",
          mr_fisher_marker
        )
      )
    ),

    paste0(
      "FDR marker and |log2FC| marker encode statistical significance and effect-size categories",
      " | n clusters = number of significant clusters containing the same gene in this heatmap"
    ),

    paste0(
      "Annotation symbols: FDR * < 0.05, ** < 0.01, *** < 0.001",
      " | |log2FC| # 0.5-<0.8, ## 0.8-<1.0, ### >=1.0"
    ),

    paste0(
      "Row clustering: Pearson correlation on row Z-scores",
      " | base distance d = ",
      row_clustering_base_distance,
      " | r_scale = ",
      row_clustering_r_scale
    ),

    paste0(
      "Same-cluster bonus = ",
      row_clustering_same_cluster_bonus,
      " -> same cluster: d x ",
      formatC(
        1 - row_clustering_same_cluster_bonus,
        format = "f",
        digits = 2
      ),
      ", different clusters: d x ",
      formatC(
        1 + row_clustering_same_cluster_bonus,
        format = "f",
        digits = 2
      ),
      " | linkage = ",
      row_clustering_linkage_method
    ),

    clustering_title
  )

  heatmap_title <- paste(
    heatmap_title_lines,
    collapse = "\n"
  )

  row_height_mm <- if (number_of_results <= 100L) {
    3.1
  } else if (number_of_results <= 300L) {
    2.35
  } else if (number_of_results <= 700L) {
    1.90
  } else {
    1.60
  }

  heatmap_body_height_mm <- number_of_results * row_height_mm
  heatmap_body_width_mm <- number_of_samples * 6.2

  pdf_width_inches <- 14

  # No short upper limit: the technical heatmap is intentionally long.
  pdf_height_inches <- max(
    14,
    (
      heatmap_body_height_mm +
        115
    ) /
      25.4
  )

  heatmap_pdf_current <- file.path(
    heatmap_output_dir,
    paste0(
      sprintf(
        "%02d",
        file_index
      ),
      "_",
      dataset_name,
      "_effectDonorGroup_",
      parameter_block,
      "_",
      variant_id,
      "_GRMRsum_4geneSetsFisher_heatmapLong.pdf"
    )
  )

  heatmap_object <- ComplexHeatmap::Heatmap(
    zscore_matrix_current,

    name = "Row Z-score",
    col = heatmap_color_function,

    top_annotation = top_annotation,
    right_annotation = right_annotation,

    cluster_columns = FALSE,

    column_split = sample_metadata$combined_group,
    cluster_column_slices = FALSE,

    column_gap = grid::unit(
      1.2,
      "mm"
    ),

    cluster_rows = cluster_rows_current,
    row_dend_reorder = row_dend_reorder_current,

    row_gap = grid::unit(
      0,
      "mm"
    ),

    row_dend_width = grid::unit(
      18,
      "mm"
    ),

    show_column_names = TRUE,
    column_names_side = "top",
    column_names_rot = 45,
    column_names_centered = TRUE,

    column_names_gp = grid::gpar(
      fontsize = 9,
      fontface = "bold"
    ),

    column_names_max_height = grid::unit(
      18,
      "mm"
    ),

    show_row_names = FALSE,

    na_col = "grey90",

    rect_gp = grid::gpar(
      col = NA
    ),

    border = FALSE,
    use_raster = FALSE,

    width = grid::unit(
      heatmap_body_width_mm,
      "mm"
    ),

    height = grid::unit(
      heatmap_body_height_mm,
      "mm"
    ),

    column_title = heatmap_title,
    column_title_side = "top",

    column_title_gp = grid::gpar(
      fontsize = 12,
      fontface = "bold",
      lineheight = 1.12
    ),

    heatmap_legend_param = list(
      title = "Row Z-score",

      at = c(
        -2,
        -1,
        0,
        1,
        2
      ),

      legend_height = grid::unit(
        46,
        "mm"
      )
    )
  )

  gr_repetition_legend <- make_gr_repetition_legend(
    fisher_marker = gr_fisher_marker
  )

  mr_repetition_legend <- make_mr_repetition_legend(
    fisher_marker = mr_fisher_marker
  )

  fdr_marker_legend <- make_fdr_marker_legend()
  log2fc_marker_legend <- make_log2fc_marker_legend()

  message(
    "Rows: ",
    number_of_results,
    " | unique genes: ",
    number_of_unique_genes,
    " | clusters: ",
    number_of_clusters
  )

  message(
    "PDF dimensions: ",
    round(
      pdf_width_inches,
      2
    ),
    " x ",
    round(
      pdf_height_inches,
      2
    ),
    " inches"
  )

  message(
    "Writing: ",
    heatmap_pdf_current
  )

  grDevices::pdf(
    file = heatmap_pdf_current,
    width = pdf_width_inches,
    height = pdf_height_inches,
    onefile = TRUE,
    useDingbats = FALSE
  )

  ComplexHeatmap::draw(
    heatmap_object,

    heatmap_legend_side = "right",
    annotation_legend_side = "right",

    merge_legends = TRUE,
    legend_grouping = "original",

    annotation_legend_list = list(
      gr_repetition_legend,
      mr_repetition_legend,
      fdr_marker_legend,
      log2fc_marker_legend
    ),

    padding = grid::unit(
      c(
        3,
        3,
        3,
        3
      ),
      "mm"
    )
  )

  grDevices::dev.off()

  if (
    !file.exists(
      heatmap_pdf_current
    ) ||
      file.info(
        heatmap_pdf_current
      )$size == 0
  ) {
    stop(
      "Heatmap PDF was not created correctly: ",
      heatmap_pdf_current,
      call. = FALSE
    )
  }

  all_cluster_ids <- names(
    custom_cluster_labels
  )

  results_per_cluster_current <- tibble::tibble(
    variant_order = file_index,
    variant_id = variant_id,
    max_mean_percent_threshold = max_mean_percent_threshold,
    max_mean_percent_filter = filter_label,
    cluster_id = all_cluster_ids,
    anatomical_region = unname(
      custom_cluster_labels[
        all_cluster_ids
      ]
    )
  ) |>
    dplyr::left_join(
      significant_current |>
        dplyr::count(
          .data$cluster_id,
          name = "n_results"
        ),
      by = "cluster_id"
    ) |>
    dplyr::mutate(
      n_results = dplyr::coalesce(
        .data$n_results,
        0L
      ),

      cluster_id = as.integer(
        .data$cluster_id
      )
    ) |>
    dplyr::arrange(
      .data$cluster_id
    )

  list(
    pdf = heatmap_pdf_current,
    summary = results_per_cluster_current,
    fisher_global = fisher_global_current,
    fisher_per_cluster = fisher_per_cluster_current,
    n_results = number_of_results,
    n_unique_genes = number_of_unique_genes,
    n_clusters = number_of_clusters
  )
}


# ==============================================================================
# 17. Generate all five heatmaps
# ==============================================================================

heatmap_outputs <- vector(
  mode = "list",
  length = nrow(
    heatmap_variants
  )
)

for (
  variant_index in
    seq_len(
      nrow(
        heatmap_variants
      )
    )
) {

  variant_current <- heatmap_variants[
    variant_index,
    ,
    drop = FALSE
  ]

  heatmap_outputs[[variant_index]] <- generate_heatmap_variant(
    file_index = variant_current$file_index[[1]],
    variant_id = variant_current$variant_id[[1]],
    max_mean_percent_threshold =
      variant_current$max_mean_percent_threshold[[1]],
    filter_label = variant_current$filter_label[[1]]
  )
}

names(
  heatmap_outputs
) <- heatmap_variants$variant_id


# ==============================================================================
# 18. Write combined results-per-cluster table
# ==============================================================================

results_per_cluster_all_variants <- dplyr::bind_rows(
  lapply(
    heatmap_outputs,
    function(x) {
      x$summary
    }
  )
) |>
  dplyr::arrange(
    .data$variant_order,
    .data$cluster_id
  )

readr::write_tsv(
  results_per_cluster_all_variants,
  results_per_cluster_tsv,
  na = "NA"
)

message(
  "\nCombined results-per-cluster table:"
)

print(
  results_per_cluster_all_variants,
  n = Inf
)


# ==============================================================================
# 19. Write combined global four-gene-set Fisher-enrichment table
# ==============================================================================

fisher_global_results_all_variants <- dplyr::bind_rows(
  lapply(
    heatmap_outputs,
    function(x) {
      x$fisher_global
    }
  )
) |>
  dplyr::group_by(
    .data$variant_id
  ) |>
  dplyr::mutate(
    FDR_BH = stats::p.adjust(
      .data$p_value,
      method = "BH"
    ),

    FDR_significance_marker = dplyr::case_when(
      !is.na(.data$FDR_BH) &
        .data$FDR_BH < 0.001 ~ "***",
      !is.na(.data$FDR_BH) &
        .data$FDR_BH < 0.01 ~ "**",
      !is.na(.data$FDR_BH) &
        .data$FDR_BH < 0.05 ~ "*",
      TRUE ~ ""
    )
  ) |>
  dplyr::ungroup() |>
  dplyr::mutate(
    test_set = factor(
      .data$test_set,
      levels = fisher_test_set_order
    )
  ) |>
  dplyr::arrange(
    .data$variant_order,
    .data$test_set
  ) |>
  dplyr::mutate(
    test_set = as.character(
      .data$test_set
    )
  ) |>
  dplyr::select(
    .data$variant_order,
    .data$variant_id,
    .data$max_mean_percent_threshold,
    .data$max_mean_percent_filter,
    .data$test_set,
    .data$background_size,
    .data$n_foreground_genes,
    .data$n_test_set_genes,
    .data$n_overlap_genes,
    .data$odds_ratio,
    .data$p_value,
    .data$significance_marker,
    .data$FDR_BH,
    .data$FDR_significance_marker,
    .data$overlap_genes
  )

readr::write_tsv(
  fisher_global_results_all_variants,
  fisher_global_results_tsv,
  na = "NA"
)

message(
  "\nGlobal four-gene-set Fisher enrichment results:"
)

print(
  fisher_global_results_all_variants,
  n = Inf
)


# ==============================================================================
# 20. Write combined per-cluster four-gene-set Fisher-enrichment table
# ==============================================================================

fisher_per_cluster_results_all_variants <- dplyr::bind_rows(
  lapply(
    heatmap_outputs,
    function(x) {
      x$fisher_per_cluster
    }
  )
) |>
  dplyr::mutate(
    test_set = factor(
      .data$test_set,
      levels = fisher_test_set_order
    )
  ) |>
  dplyr::arrange(
    .data$variant_order,
    .data$cluster_id,
    .data$test_set
  ) |>
  dplyr::mutate(
    test_set = as.character(
      .data$test_set
    )
  )

readr::write_tsv(
  fisher_per_cluster_results_all_variants,
  fisher_per_cluster_results_tsv,
  na = "NA"
)

message(
  "\nPer-cluster four-gene-set Fisher enrichment results:"
)

print(
  fisher_per_cluster_results_all_variants,
  n = Inf
)


# ==============================================================================
# 21. Validate outputs and final report
# ==============================================================================

heatmap_pdf_files <- vapply(
  heatmap_outputs,
  function(x) {
    x$pdf
  },
  FUN.VALUE = character(1)
)

expected_output_files <- c(
  heatmap_pdf_files,
  results_per_cluster_tsv,
  fisher_global_results_tsv,
  fisher_per_cluster_results_tsv
)

missing_output_files <- expected_output_files[
  !file.exists(
    expected_output_files
  )
]

if (length(missing_output_files) > 0L) {
  stop(
    "Missing output file(s):\n",
    paste(
      missing_output_files,
      collapse = "\n"
    ),
    call. = FALSE
  )
}

empty_output_files <- expected_output_files[
  file.info(
    expected_output_files
  )$size == 0
]

if (length(empty_output_files) > 0L) {
  stop(
    "Empty output file(s):\n",
    paste(
      empty_output_files,
      collapse = "\n"
    ),
    call. = FALSE
  )
}

message("\n")
message(
  paste(
    rep(
      "=",
      78
    ),
    collapse = ""
  )
)

message(
  "All five heatmaps completed successfully."
)

message(
  "Output directory:"
)

message(
  normalizePath(
    heatmap_output_dir,
    mustWork = TRUE
  )
)

message("\nHeatmap PDFs:")

for (heatmap_file in heatmap_pdf_files) {
  message(
    normalizePath(
      heatmap_file,
      mustWork = TRUE
    )
  )
}

message(
  "\nResults-per-cluster table:"
)

message(
  normalizePath(
    results_per_cluster_tsv,
    mustWork = TRUE
  )
)

message(
  "\nGlobal four-gene-set Fisher-enrichment table:"
)

message(
  normalizePath(
    fisher_global_results_tsv,
    mustWork = TRUE
  )
)

message(
  "\nPer-cluster four-gene-set Fisher-enrichment table:"
)

message(
  normalizePath(
    fisher_per_cluster_results_tsv,
    mustWork = TRUE
  )
)


# ==============================================================================
# End
# ==============================================================================
