#!/usr/bin/env Rscript

# ==============================================================================
# 01_heatmap_interaction_FDR005_perCluster_oneHeatmap_FDRlegendOnly.R
#
# One heatmap for significant Group x Sex interaction results from the
# cluster-specific pseudobulk edgeR analysis.
#
# IMPORTANT
#   This version reads everything from the two RData files generated by the
#   edgeR workflow:
#
#   1. *_edgeRResults.RData
#      - edgeR_perCluster_combinedResults
#      - edgeR_perCluster_testDefinitions
#
#   2. *_edgeRModelObjects.RData
#      - edgeR_perCluster_modelObjects
#      - DGEList for every completed cluster
#      - sample metadata and TMM normalization factors
#
#   It does NOT search for separate sample-level metadata TSV files.
#
# ROWS
#   Significant cluster-gene interaction results at FDR < 0.05.
#   The same gene can occur more than once when significant in several clusters.
#
# COLUMNS
#   Samples ordered as:
#     Male Neurotypical -> Male ASD -> Female Neurotypical -> Female ASD
#
# HEATMAP VALUES
#   TMM-normalized CPM per sample and cluster
#   -> log2(CPM + 1)
#   -> row-wise Z-score
#   -> clipped to [-2, 2]
#
# ROW ORGANIZATION
#   Rows are split first by source cluster and then by interaction logFC sign.
#   Genes are hierarchically clustered separately inside every resulting block.
#
# ROW ANNOTATIONS
#   - source cluster, using manual-clustering colours;
#   - maximum mean percent-positive spots across the four Sex x Group cells;
#   - interaction logFC direction.
#
# LEGEND COUNTS
#   Source-cluster legend:
#     n = number of significant cluster-gene interaction results in the cluster.
#
#   FDR marker legend:
#     FDR < 0.05  (n = all displayed results satisfying FDR < 0.05)
#     FDR < 0.01  (n = all displayed results satisfying FDR < 0.01)
#     FDR < 0.001 (n = all displayed results satisfying FDR < 0.001)
#
#   FDR threshold counts are cumulative and refer to cluster-gene results.
#   No UP/DOWN subdivision is used for the interaction effect.
# ==============================================================================

options(stringsAsFactors = FALSE)


# ==============================================================================
# 1. Packages
# ==============================================================================

required_packages <- c(
  "dplyr",
  "tibble",
  "readr",
  "edgeR",
  "ComplexHeatmap",
  "circlize",
  "grid"
)

missing_packages <- required_packages[
  !vapply(
    required_packages,
    requireNamespace,
quietly = TRUE,
FUN.VALUE = logical(1)
  )
]

if (length(missing_packages) > 0L) {
  stop(
    "Missing required packages: ",
    paste(missing_packages, collapse = ", "),
call. = FALSE
  )
}

suppressPackageStartupMessages({
  library(dplyr)
  library(tibble)
  library(readr)
  library(edgeR)
  library(ComplexHeatmap)
  library(circlize)
  library(grid)
})


# ==============================================================================
# 2. Analysis configuration
# ==============================================================================

project_root <- "/home/mateusz/projects/ippas-kunevicius-spatial"
dataset_name <- "maternalFMT_n16samples"

clustering_name <-
  "logNormalizeVstHvg2000_ccaDims20K20PruneSNN0067_leidenRes040"

fdr_threshold <- 0.05
zscore_lower_limit <- -2
zscore_upper_limit <- 2

# Missing sample-cluster CPM values occur when an entire sample x cluster
# pseudobulk was not retained in the cluster-specific DGEList, for example
# because it did not reach min_spots_per_sample_cluster. This is not gene-level
# edgeR filtering. When enabled, missing CPM values are imputed per heatmap row
# by the mean CPM of available samples in the same Sex x FMT donor-group cell.
impute_missing_by_group_mean <- FALSE
imputation_fallback_to_row_mean <- TRUE

# Row-clustering parameters.
# Base distance: 2 - Pearson correlation.
# Distances for rows from the same source cluster are multiplied by 0.75,
# whereas distances for rows from different clusters are multiplied by 1.25.
row_clustering_base_distance <- "2 - r"
row_clustering_r_scale <- 1
row_clustering_same_cluster_bonus <- 0.20
row_clustering_linkage_method <- "complete"

# Exact clustering information for the title.
clustering_title <- paste(
  "LogNormalize + VST | HVG = 2000 | CCA dims = 20 |",
  "k = 20 | prune.SNN = 0.0667 | Leiden resolution = 0.40"
)


# ==============================================================================
# 3. Cluster colours and anatomical labels
# ==============================================================================

custom_cluster_colors <- c(
  "1"  = "#e66063",
  "2"  = "#407ba7",
  "3"  = "#31cb00",
  "4"  = "#adb5bd",
  "5"  = "#9e0059",
  "6"  = "#b5838d",
  "7"  = "#002962",
  "8"  = "#004e89",
  "9"  = "#d02224",
  "10" = "#ff9505",
  "11" = "#9c191b",
  "12" = "#e85d04",
  "13" = "#119822",
  "14" = "#6B1E2D",
  "15" = "#ffd100",
  "16" = "#1e441e"
)

custom_cluster_labels <- c(
  "1"  = "posterior & sensory relay thalamic nuclei",
  "2"  = "isocortex, layers 4 & 5",
  "3"  = "cortical layers 1 & hippocampal neuropil",
  "4"  = "Fiber tracts",
  "5"  = "cortical subplate & deep olfactory areas",
  "6"  = "hypothalamus",
  "7"  = "isocortex, layer 6",
  "8"  = "isocortex, layer 2/3",
  "9"  = "reticular, ventral geniculate & habenular region",
  "10" = "striatum-like amygdala nuclei",
  "11" = "medial thalamic nuclei",
  "12" = "caudoputamen",
  "13" = "hippocampal CA fields, pyramidal layer",
  "14" = "meninges & vasculature",
  "15" = "ventricles",
  "16" = "dentate gyrus"
)


# ==============================================================================
# 4. Input and output paths
# ==============================================================================

statistics_dir <- file.path(
  project_root,
  "results",
  dataset_name,
  "pseudobulkPerCluster_geneCounts_edgeR_twoFactorInteraction",
  clustering_name,
  "01_statistics"
)

analysis_prefix <- paste0(
  dataset_name,
  "_",
  clustering_name,
  "_pseudobulkPerCluster_geneCounts_edgeR_twoFactorInteraction"
)

edgeR_results_rdata_file <- file.path(
  statistics_dir,
  "03_edgeRResults",
  paste0(
    analysis_prefix,
    "_edgeRResults.RData"
  )
)

edgeR_model_objects_rdata_file <- file.path(
  statistics_dir,
  "05_objects",
  paste0(
    analysis_prefix,
    "_edgeRModelObjects.RData"
  )
)

heatmap_output_dir <- file.path(
  project_root,
  "results",
  dataset_name,
  "pseudobulkPerCluster_geneCounts_edgeR_twoFactorInteraction",
  clustering_name,
  "02_heatmaps",
  "01_interaction",
  "FDR005"
)

dir.create(
  heatmap_output_dir,
recursive = TRUE,
showWarnings = FALSE
)

required_input_files <- c(
  edgeR_results_rdata_file,
  edgeR_model_objects_rdata_file
)

missing_input_files <- required_input_files[
  !file.exists(required_input_files)
]

if (length(missing_input_files) > 0L) {
  stop(
    "Missing required RData file(s):\n",
    paste(missing_input_files, collapse = "\n"),
call. = FALSE
  )
}


# ==============================================================================
# 5. Output files
# ==============================================================================

heatmap_pdf <- file.path(
  heatmap_output_dir,
  paste0(
    "01_",
    dataset_name,
    "_",
    clustering_name,
    "_interaction_FDRlt005_TMMCPM_rowZscore_heatmap.pdf"
  )
)

selected_results_tsv <- file.path(
  heatmap_output_dir,
  paste0(
    "02_",
    dataset_name,
    "_interaction_FDRlt005_selectedClusterGeneResults.tsv"
  )
)

row_annotations_tsv <- file.path(
  heatmap_output_dir,
  paste0(
    "03_",
    dataset_name,
    "_interaction_FDRlt005_rowAnnotations.tsv"
  )
)

zscore_matrix_tsv <- file.path(
  heatmap_output_dir,
  paste0(
    "04_",
    dataset_name,
    "_interaction_FDRlt005_rowZscoreMatrix.tsv"
  )
)

sample_order_tsv <- file.path(
  heatmap_output_dir,
  paste0(
    "05_",
    dataset_name,
    "_interaction_FDRlt005_sampleOrder.tsv"
  )
)

summary_tsv <- file.path(
  heatmap_output_dir,
  paste0(
    "06_",
    dataset_name,
    "_interaction_FDRlt005_heatmapSummary.tsv"
  )
)


# ==============================================================================
# 6. Helper functions
# ==============================================================================

find_interaction_test_id <- function(test_definitions) {

  required_columns <- c(
    "test_id",
    "sheet_name",
    "comparison"
  )

  missing_columns <- setdiff(
    required_columns,
    colnames(test_definitions)
  )

  if (length(missing_columns) > 0L) {
    stop(
      "Test-definition table is missing: ",
      paste(missing_columns, collapse = ", "),
call. = FALSE
    )
  }

  candidate_rows <- test_definitions |>
    dplyr::filter(
      grepl("interaction", .data$test_id, ignore.case = TRUE) |
        grepl("interaction", .data$sheet_name, ignore.case = TRUE) |
        grepl("interaction", .data$comparison, ignore.case = TRUE)
    )

  if (nrow(candidate_rows) != 1L) {
    stop(
      "Could not uniquely identify the interaction test. Candidates found: ",
      nrow(candidate_rows),
call. = FALSE
    )
  }

  as.character(candidate_rows$test_id[[1]])
}


calculate_row_zscores <- function(
expression_matrix,
lower_limit = -2,
upper_limit = 2
) {

  output_matrix <- matrix(
    NA_real_,
nrow = nrow(expression_matrix),
ncol = ncol(expression_matrix),
dimnames = dimnames(expression_matrix)
  )

  for (row_index in seq_len(nrow(expression_matrix))) {

    values <- as.numeric(expression_matrix[row_index, ])
    finite_values <- is.finite(values)

    if (sum(finite_values) < 2L) {
      output_matrix[row_index, finite_values] <- 0
      next
    }

    row_mean <- mean(values[finite_values])
    row_sd <- stats::sd(values[finite_values])

    if (!is.finite(row_sd) || row_sd == 0) {
      output_matrix[row_index, finite_values] <- 0
      next
    }

    output_matrix[row_index, finite_values] <-
      (values[finite_values] - row_mean) / row_sd
  }

  output_matrix[
    is.finite(output_matrix) & output_matrix < lower_limit
  ] <- lower_limit

  output_matrix[
    is.finite(output_matrix) & output_matrix > upper_limit
  ] <- upper_limit

  output_matrix
}


impute_cpm_by_group_mean <- function(
cpm_matrix,
sample_metadata,
fallback_to_row_mean = TRUE
) {

  required_metadata_columns <- c(
    "sample_ID",
    "combined_group"
  )

  missing_metadata_columns <- setdiff(
    required_metadata_columns,
    colnames(sample_metadata)
  )

  if (length(missing_metadata_columns) > 0L) {
    stop(
      "Sample metadata is missing columns required for imputation: ",
      paste(missing_metadata_columns, collapse = ", "),
call. = FALSE
    )
  }

  metadata_aligned <- sample_metadata[
    match(colnames(cpm_matrix), sample_metadata$sample_ID),
    ,
drop = FALSE
  ]

  if (anyNA(metadata_aligned$sample_ID)) {
    stop(
      "Could not align sample metadata to CPM matrix columns for imputation.",
call. = FALSE
    )
  }

  group_labels <- as.character(metadata_aligned$combined_group)

  if (anyNA(group_labels)) {
    stop(
      "Combined Sex x FMT donor-group labels contain NA values.",
call. = FALSE
    )
  }

  imputed_matrix <- cpm_matrix
  imputation_mask <- matrix(
    FALSE,
nrow = nrow(cpm_matrix),
ncol = ncol(cpm_matrix),
dimnames = dimnames(cpm_matrix)
  )

  for (row_index in seq_len(nrow(imputed_matrix))) {

    for (group_current in unique(group_labels)) {

      group_columns <- which(group_labels == group_current)
      group_values <- imputed_matrix[row_index, group_columns]

      missing_in_group <- is.na(group_values)
      observed_in_group <- is.finite(group_values)

      if (any(missing_in_group) && any(observed_in_group)) {
        group_mean <- mean(
          group_values[observed_in_group],
na.rm = TRUE
        )

        target_columns <- group_columns[missing_in_group]
        imputed_matrix[row_index, target_columns] <- group_mean
        imputation_mask[row_index, target_columns] <- TRUE
      }
    }

    remaining_missing <- which(is.na(imputed_matrix[row_index, ]))

    if (
      length(remaining_missing) > 0L &&
        isTRUE(fallback_to_row_mean)
    ) {
      observed_row_values <- imputed_matrix[
        row_index,
        is.finite(imputed_matrix[row_index, ])
      ]

      if (length(observed_row_values) > 0L) {
        row_mean <- mean(observed_row_values)
        imputed_matrix[row_index, remaining_missing] <- row_mean
        imputation_mask[row_index, remaining_missing] <- TRUE
      }
    }
  }

  remaining_missing_count <- sum(is.na(imputed_matrix))

  if (remaining_missing_count > 0L) {
    stop(
      "Imputation left ",
      remaining_missing_count,
      " missing CPM value(s).",
call. = FALSE
    )
  }

  list(
matrix = imputed_matrix,
mask = imputation_mask,
number_imputed = sum(imputation_mask),
number_rows_with_imputation = sum(rowSums(imputation_mask) > 0L)
  )
}


modified_correlation_distance <- function(
expression_matrix,
cluster_labels,
base_distance = "2 - r",
r_scale = 1,
same_cluster_bonus = 0.25
) {

  if (!is.matrix(expression_matrix)) {
    expression_matrix <- as.matrix(expression_matrix)
  }

  if (nrow(expression_matrix) <= 1L) {
    return(stats::as.dist(matrix(0, nrow = 1, ncol = 1)))
  }

  cluster_labels <- as.character(cluster_labels)

  if (length(cluster_labels) != nrow(expression_matrix)) {
    stop(
      "The number of cluster labels must equal the number of heatmap rows.",
call. = FALSE
    )
  }

  if (!is.numeric(r_scale) || length(r_scale) != 1L || !is.finite(r_scale)) {
    stop("`r_scale` must be one finite numeric value.", call. = FALSE)
  }

  if (
    !is.numeric(same_cluster_bonus) ||
      length(same_cluster_bonus) != 1L ||
      !is.finite(same_cluster_bonus) ||
      same_cluster_bonus < 0 ||
      same_cluster_bonus >= 1
  ) {
    stop(
      "`same_cluster_bonus` must be a finite number in [0, 1).",
call. = FALSE
    )
  }

  cor_mat <- suppressWarnings(
    stats::cor(
      t(expression_matrix),
method = "pearson",
use = "pairwise.complete.obs"
    )
  )

  cor_mat[!is.finite(cor_mat)] <- 0
  diag(cor_mat) <- 1

  base_dist <- if (identical(base_distance, "2 - r")) {
    2 - (cor_mat * r_scale)
  } else if (identical(base_distance, "1 - r")) {
    1 - (cor_mat * r_scale)
  } else {
    stop(
      "`base_distance` must be either '2 - r' or '1 - r'.",
call. = FALSE
    )
  }

  same_cluster_matrix <- outer(
    cluster_labels,
    cluster_labels,
FUN = "=="
  )

  dist_mat <- base_dist

  dist_mat[same_cluster_matrix] <-
    base_dist[same_cluster_matrix] * (1 - same_cluster_bonus)

  dist_mat[!same_cluster_matrix] <-
    base_dist[!same_cluster_matrix] * (1 + same_cluster_bonus)

  diag(dist_mat) <- 0
  dist_mat[dist_mat < 0] <- 0

  stats::as.dist(dist_mat)
}


create_modified_row_hclust <- function(
expression_matrix,
annotation_table,
base_distance = "2 - r",
r_scale = 1,
same_cluster_bonus = 0.25,
linkage_method = "complete"
) {

  matched_annotation <- annotation_table[
    match(rownames(expression_matrix), annotation_table$row_id),
    ,
drop = FALSE
  ]

  if (
    nrow(matched_annotation) != nrow(expression_matrix) ||
      anyNA(matched_annotation$row_id) ||
      anyNA(matched_annotation$cluster_id)
  ) {
    stop(
      "Failed to match source-cluster annotations to all heatmap rows.",
call. = FALSE
    )
  }

  modified_distance <- modified_correlation_distance(
expression_matrix = expression_matrix,
cluster_labels = matched_annotation$cluster_id,
base_distance = base_distance,
r_scale = r_scale,
same_cluster_bonus = same_cluster_bonus
  )

  stats::hclust(
    modified_distance,
method = linkage_method
  )
}


format_cluster_label <- function(cluster_id) {
  paste0(
    "C",
    cluster_id,
    " | ",
    unname(custom_cluster_labels[cluster_id])
  )
}


make_fdr_marker_legend <- function(significant_results) {

  required_columns <- c(
    "FDR"
  )

  missing_columns <- setdiff(
    required_columns,
    colnames(significant_results)
  )

  if (length(missing_columns) > 0L) {
    stop(
      "FDR legend input is missing required column(s): ",
      paste(missing_columns, collapse = ", "),
      call. = FALSE
    )
  }

  n_fdr_005 <- sum(
    !is.na(significant_results$FDR) &
      significant_results$FDR < 0.05
  )

  n_fdr_001 <- sum(
    !is.na(significant_results$FDR) &
      significant_results$FDR < 0.01
  )

  n_fdr_0001 <- sum(
    !is.na(significant_results$FDR) &
      significant_results$FDR < 0.001
  )

  ComplexHeatmap::Legend(
    title = "FDR marker",

    labels = c(
      paste0(
        "FDR < 0.05 (n = ",
        n_fdr_005,
        ")"
      ),
      paste0(
        "FDR < 0.01 (n = ",
        n_fdr_001,
        ")"
      ),
      paste0(
        "FDR < 0.001 (n = ",
        n_fdr_0001,
        ")"
      )
    ),

    graphics = list(
      function(x, y, w, h) {
        grid::grid.text(
          "*",
          x = x,
          y = y,
          gp = grid::gpar(
            fontsize = 10,
            fontface = "bold"
          )
        )
      },

      function(x, y, w, h) {
        grid::grid.text(
          "**",
          x = x,
          y = y,
          gp = grid::gpar(
            fontsize = 10,
            fontface = "bold"
          )
        )
      },

      function(x, y, w, h) {
        grid::grid.text(
          "***",
          x = x,
          y = y,
          gp = grid::gpar(
            fontsize = 10,
            fontface = "bold"
          )
        )
      }
    ),

    grid_width = grid::unit(
      7,
      "mm"
    ),

    grid_height = grid::unit(
      4,
      "mm"
    ),

    title_gp = grid::gpar(
      fontsize = 9,
      fontface = "bold"
    ),

    labels_gp = grid::gpar(
      fontsize = 8
    )
  )
}


# ==============================================================================
# 7. Load the two RData files
# ==============================================================================

message("Loading edgeR results RData:")
message(edgeR_results_rdata_file)
load(edgeR_results_rdata_file)

message("\nLoading edgeR model-object RData:")
message(edgeR_model_objects_rdata_file)
load(edgeR_model_objects_rdata_file)

required_objects <- c(
  "edgeR_perCluster_combinedResults",
  "edgeR_perCluster_testDefinitions",
  "edgeR_perCluster_modelObjects"
)

missing_objects <- required_objects[
  !vapply(required_objects, exists, logical(1))
]

if (length(missing_objects) > 0L) {
  stop(
    "Required object(s) missing after loading RData files: ",
    paste(missing_objects, collapse = ", "),
call. = FALSE
  )
}


# ==============================================================================
# 8. Select significant interaction results
# ==============================================================================

interaction_test_id <- find_interaction_test_id(
  edgeR_perCluster_testDefinitions
)

message("\nSelected interaction test_id: ", interaction_test_id)

if (!interaction_test_id %in% names(edgeR_perCluster_combinedResults)) {
  stop(
    "Interaction test is absent from edgeR_perCluster_combinedResults: ",
    interaction_test_id,
call. = FALSE
  )
}

interaction_results <-
  edgeR_perCluster_combinedResults[[interaction_test_id]] |>
  tibble::as_tibble()

required_interaction_columns <- c(
  "cluster_id",
  "ensembl_gene_id",
  "gene",
  "logFC",
  "PValue",
  "FDR",
  "mean_percent_positive_spots_Male_Neurotypical",
  "mean_percent_positive_spots_Male_ASD",
  "mean_percent_positive_spots_Female_Neurotypical",
  "mean_percent_positive_spots_Female_ASD"
)

missing_interaction_columns <- setdiff(
  required_interaction_columns,
  colnames(interaction_results)
)

if (length(missing_interaction_columns) > 0L) {
  stop(
    "Interaction results are missing required columns: ",
    paste(missing_interaction_columns, collapse = ", "),
call. = FALSE
  )
}

significant_interaction <- interaction_results |>
  dplyr::filter(
    !is.na(.data$FDR),
    .data$FDR < fdr_threshold
  ) |>
  dplyr::mutate(
cluster_id = as.character(.data$cluster_id),
interaction_direction = dplyr::case_when(
      .data$logFC > 0 ~ "Positive logFC",
      .data$logFC < 0 ~ "Negative logFC",
      TRUE ~ "Zero logFC"
    ),
max_mean_percent = pmax(
      .data$mean_percent_positive_spots_Male_Neurotypical,
      .data$mean_percent_positive_spots_Male_ASD,
      .data$mean_percent_positive_spots_Female_Neurotypical,
      .data$mean_percent_positive_spots_Female_ASD,
na.rm = TRUE
    )
  ) |>
  dplyr::arrange(
    as.integer(.data$cluster_id),
    factor(
      .data$interaction_direction,
levels = c(
        "Positive logFC",
        "Negative logFC",
        "Zero logFC"
      )
    ),
    .data$FDR,
    dplyr::desc(abs(.data$logFC))
  )

if (nrow(significant_interaction) == 0L) {
  stop(
    "No interaction result satisfies FDR < ",
    fdr_threshold,
call. = FALSE
  )
}

significant_clusters <- sort(
  unique(as.integer(significant_interaction$cluster_id))
)

significant_cluster_ids <- as.character(significant_clusters)

missing_model_clusters <- setdiff(
  significant_cluster_ids,
  names(edgeR_perCluster_modelObjects)
)

if (length(missing_model_clusters) > 0L) {
  stop(
    "Model RData is missing significant cluster(s): ",
    paste(missing_model_clusters, collapse = ", "),
call. = FALSE
  )
}

message(
  "Significant cluster-gene results: ",
  nrow(significant_interaction)
)

message(
  "Unique genes: ",
  length(unique(significant_interaction$gene))
)

message(
  "Significant clusters: ",
  paste(significant_cluster_ids, collapse = ", ")
)


# ==============================================================================
# 9. Extract sample metadata directly from DGEList objects
# ==============================================================================

sample_metadata_list <- lapply(
  significant_cluster_ids,
  function(cluster_id_current) {

    model_object <-
      edgeR_perCluster_modelObjects[[cluster_id_current]]

    if (is.null(model_object$dge)) {
      stop(
        "DGEList is missing for cluster ",
        cluster_id_current,
call. = FALSE
      )
    }

    dge_samples <- model_object$dge$samples |>
      tibble::rownames_to_column("dge_rowname") |>
      tibble::as_tibble()

    required_dge_sample_columns <- c(
      "sample_ID",
      "fmt_donor_group",
      "sex"
    )

    missing_dge_sample_columns <- setdiff(
      required_dge_sample_columns,
      colnames(dge_samples)
    )

    if (length(missing_dge_sample_columns) > 0L) {
      stop(
        "DGEList sample metadata for cluster ",
        cluster_id_current,
        " is missing: ",
        paste(missing_dge_sample_columns, collapse = ", "),
call. = FALSE
      )
    }

    dge_samples |>
      dplyr::transmute(
sample_ID = as.character(.data$sample_ID),
fmt_donor_group = as.character(.data$fmt_donor_group),
sex = as.character(.data$sex)
      )
  }
)

sample_metadata <- sample_metadata_list |>
  dplyr::bind_rows() |>
  dplyr::distinct(
    .data$sample_ID,
    .data$fmt_donor_group,
    .data$sex
  )

metadata_conflicts <- sample_metadata |>
  dplyr::count(.data$sample_ID, name = "n_metadata_rows") |>
  dplyr::filter(.data$n_metadata_rows > 1L)

if (nrow(metadata_conflicts) > 0L) {
  stop(
    "Conflicting Sex/Group metadata found for sample(s): ",
    paste(metadata_conflicts$sample_ID, collapse = ", "),
call. = FALSE
  )
}

sample_metadata <- sample_metadata |>
  dplyr::mutate(
sex = factor(
      .data$sex,
levels = c("Male", "Female")
    ),
fmt_donor_group = factor(
      .data$fmt_donor_group,
levels = c("Neurotypical", "ASD")
    )
  )

if (anyNA(sample_metadata$sex)) {
  stop("Unexpected sex value in DGEList metadata.", call. = FALSE)
}

if (anyNA(sample_metadata$fmt_donor_group)) {
  stop(
    "Unexpected fmt_donor_group value in DGEList metadata.",
call. = FALSE
  )
}

sample_metadata <- sample_metadata |>
  dplyr::arrange(
    .data$sex,
    .data$fmt_donor_group,
    .data$sample_ID
  ) |>
  dplyr::mutate(
sample_order = dplyr::row_number(),
combined_group = factor(
      paste(
        as.character(.data$sex),
        as.character(.data$fmt_donor_group),
sep = "_"
      ),
levels = c(
        "Male_Neurotypical",
        "Male_ASD",
        "Female_Neurotypical",
        "Female_ASD"
      )
    )
  )

sample_order <- as.character(sample_metadata$sample_ID)

message("\nSample order used in the heatmap:")
print(
  sample_metadata |>
    dplyr::select(
      .data$sample_order,
      .data$sample_ID,
      .data$sex,
      .data$fmt_donor_group,
      .data$combined_group
    ),
n = Inf
)


# ==============================================================================
# 10. Calculate sample-level TMM-CPM directly from every cluster DGEList
# ==============================================================================

cluster_cpm_matrices <- lapply(
  significant_cluster_ids,
  function(cluster_id_current) {

    dge <-
      edgeR_perCluster_modelObjects[[cluster_id_current]]$dge

    cpm_matrix <- edgeR::cpm(
      dge,
normalized.lib.sizes = TRUE,
log = FALSE
    )

    if (is.null(rownames(cpm_matrix))) {
      stop(
        "TMM-CPM matrix has no gene IDs for cluster ",
        cluster_id_current,
call. = FALSE
      )
    }

    if (is.null(colnames(cpm_matrix))) {
      stop(
        "TMM-CPM matrix has no sample IDs for cluster ",
        cluster_id_current,
call. = FALSE
      )
    }

    cpm_matrix
  }
)

names(cluster_cpm_matrices) <- significant_cluster_ids


# ==============================================================================
# 11. Build one cluster-gene x sample CPM matrix
# ==============================================================================

sample_level_cpm_matrix <- matrix(
  NA_real_,
nrow = nrow(significant_interaction),
ncol = length(sample_order),
dimnames = list(
    NULL,
    sample_order
  )
)

row_ids <- paste0(
  ifelse(
    is.na(significant_interaction$gene) |
      significant_interaction$gene == "",
    significant_interaction$ensembl_gene_id,
    significant_interaction$gene
  ),
  " [C",
  significant_interaction$cluster_id,
  "]"
)

# The cluster tag makes repeated gene symbols unambiguous without changing
# the official gene symbol itself, e.g. Ttr [C14] versus Ttr [C15].
if (anyDuplicated(row_ids) > 0L) {
  duplicated_labels <- unique(row_ids[duplicated(row_ids)])
  stop(
    "Duplicated gene-cluster row labels detected: ",
    paste(duplicated_labels, collapse = ", "),
call. = FALSE
  )
}
rownames(sample_level_cpm_matrix) <- row_ids

for (row_index in seq_len(nrow(significant_interaction))) {

  current_cluster <-
    significant_interaction$cluster_id[[row_index]]

  current_gene_id <-
    significant_interaction$ensembl_gene_id[[row_index]]

  current_cpm_matrix <-
    cluster_cpm_matrices[[current_cluster]]

  gene_match <- match(
    current_gene_id,
    rownames(current_cpm_matrix)
  )

  if (is.na(gene_match)) {
    stop(
      "Gene ",
      current_gene_id,
      " is missing from the tested DGEList genes for cluster ",
      current_cluster,
call. = FALSE
    )
  }

  available_samples <- intersect(
    sample_order,
    colnames(current_cpm_matrix)
  )

  sample_level_cpm_matrix[
    row_index,
    available_samples
  ] <- current_cpm_matrix[
    gene_match,
    available_samples,
drop = TRUE
  ]
}

if (all(is.na(sample_level_cpm_matrix))) {
  stop(
    "The complete cluster-gene CPM matrix contains only NA values.",
call. = FALSE
  )
}

number_missing_before_imputation <- sum(is.na(sample_level_cpm_matrix))
number_imputed_values <- 0L
number_rows_with_imputation <- 0L

if (isTRUE(impute_missing_by_group_mean)) {

  imputation_output <- impute_cpm_by_group_mean(
cpm_matrix = sample_level_cpm_matrix,
sample_metadata = sample_metadata,
fallback_to_row_mean = imputation_fallback_to_row_mean
  )

  sample_level_cpm_matrix <- imputation_output$matrix
  imputation_mask <- imputation_output$mask
  number_imputed_values <- imputation_output$number_imputed
  number_rows_with_imputation <-
    imputation_output$number_rows_with_imputation

  message(
    "Missing sample-cluster CPM values before imputation: ",
    number_missing_before_imputation
  )
  message(
    "CPM values imputed by within-group mean: ",
    number_imputed_values
  )
  message(
    "Heatmap rows containing at least one imputed value: ",
    number_rows_with_imputation
  )

} else {

  imputation_mask <- matrix(
    FALSE,
nrow = nrow(sample_level_cpm_matrix),
ncol = ncol(sample_level_cpm_matrix),
dimnames = dimnames(sample_level_cpm_matrix)
  )
}


# ==============================================================================
# 12. Transformation for visualization
# ==============================================================================

log2_cpm_matrix <- log2(sample_level_cpm_matrix + 1)

zscore_matrix <- calculate_row_zscores(
expression_matrix = log2_cpm_matrix,
lower_limit = zscore_lower_limit,
upper_limit = zscore_upper_limit
)


# ==============================================================================
# 13. Row annotations
# ==============================================================================

# Repetition is purely an annotation:
# number of significant interaction clusters containing the same gene.
gene_repetition_table <- significant_interaction |>
  dplyr::count(
    .data$ensembl_gene_id,
name = "n_repetition"
  )

row_annotation_table <- significant_interaction |>
  dplyr::transmute(
row_id = row_ids,
ensembl_gene_id = .data$ensembl_gene_id,
cluster_id = .data$cluster_id,

cluster_label = vapply(
      .data$cluster_id,
      format_cluster_label,
FUN.VALUE = character(1)
    ),

interaction_direction = .data$interaction_direction,
logFC = .data$logFC,
abs_logFC = abs(.data$logFC),
PValue = .data$PValue,
FDR = .data$FDR,
max_mean_percent = .data$max_mean_percent,

fdr_symbol = dplyr::case_when(
      .data$FDR < 0.001 ~ "***",
      .data$FDR < 0.01 ~ "**",
      .data$FDR < 0.05 ~ "*",
      TRUE ~ ""
    )
  ) |>
  dplyr::left_join(
    gene_repetition_table,
by = "ensembl_gene_id"
  )

cluster_factor_levels <- as.character(
  significant_clusters
)

cluster_annotation_colors <- custom_cluster_colors[
  cluster_factor_levels
]

names(
  cluster_annotation_colors
) <- cluster_factor_levels


# ------------------------------------------------------------------------------
# 13a. Source-cluster legend: number of significant genes per cluster
# ------------------------------------------------------------------------------

cluster_result_counts <- table(
  factor(
    row_annotation_table$cluster_id,
levels = cluster_factor_levels
  )
)

cluster_legend_labels <- paste0(
  "C",
  cluster_factor_levels,
  " (n = ",
  as.integer(
    cluster_result_counts
  ),
  "): ",
  unname(
    custom_cluster_labels[
      cluster_factor_levels
    ]
  )
)


# ------------------------------------------------------------------------------
# 13b. Max mean % annotation with values printed inside purple cells
# ------------------------------------------------------------------------------

max_mean_percent_color_function <- circlize::colorRamp2(
  c(
    0,
    25,
    50,
    75,
    100
  ),
  c(
    "#F3E8FF",
    "#DDD6FE",
    "#C084FC",
    "#9333EA",
    "#4C1D95"
  )
)

annotation_row_font_size <- if (
  nrow(
    row_annotation_table
  ) <= 80L
) {
  7.2
} else if (
  nrow(
    row_annotation_table
  ) <= 180L
) {
  5.8
} else {
  4.8
}

percent_annotation_labels <- ifelse(
  is.na(
    row_annotation_table$max_mean_percent
  ),
  "NA",
  paste0(
    round(
      row_annotation_table$max_mean_percent
    ),
    "%"
  )
)

percent_annotation_text_colour <- ifelse(
  !is.na(
    row_annotation_table$max_mean_percent
  ) &
    row_annotation_table$max_mean_percent > 70,
  "white",
  "black"
)

max_mean_percent_annotation <- ComplexHeatmap::AnnotationFunction(
which = "row",

width = grid::unit(
    5.5,
    "mm"
  ),

var_import = list(
values = row_annotation_table$max_mean_percent,
labels = percent_annotation_labels,
text_colours = percent_annotation_text_colour,
colour_function = max_mean_percent_color_function,
font_size = annotation_row_font_size
  ),

fun = function(index) {

    n_current <- length(
      index
    )

    y_positions <- 1 - (
      seq_len(
        n_current
      ) - 0.5
    ) / n_current

    current_values <- values[
      index
    ]

    current_labels <- labels[
      index
    ]

    current_text_colours <- text_colours[
      index
    ]

    current_fill <- rep(
      "grey90",
      n_current
    )

    finite_values <- is.finite(
      current_values
    )

    current_fill[
      finite_values
    ] <- colour_function(
      current_values[
        finite_values
      ]
    )

    grid::grid.rect(
x = grid::unit(
        0.5,
        "npc"
      ),

y = grid::unit(
        y_positions,
        "npc"
      ),

width = grid::unit(
        1,
        "npc"
      ),

height = grid::unit(
        1 / n_current,
        "npc"
      ),

gp = grid::gpar(
fill = current_fill,
col = NA
      )
    )

    grid::grid.text(
label = current_labels,

x = grid::unit(
        0.5,
        "npc"
      ),

y = grid::unit(
        y_positions,
        "npc"
      ),

gp = grid::gpar(
col = current_text_colours,
fontsize = font_size,
fontface = "bold"
      )
    )
  }
)


# ------------------------------------------------------------------------------
# 13c. Complete right-side annotation block
# ------------------------------------------------------------------------------

gene_symbol_annotation_width <-
  ComplexHeatmap::max_text_width(
    row_ids,
gp = grid::gpar(
fontsize = annotation_row_font_size
    )
  ) +
  grid::unit(
    1.5,
    "mm"
  )

right_annotation <- ComplexHeatmap::rowAnnotation(
Cluster = row_annotation_table$cluster_id,

  `Max mean %` = max_mean_percent_annotation,

  `FDR marker` = ComplexHeatmap::anno_text(
    row_annotation_table$fdr_symbol,

location = grid::unit(
      0.5,
      "npc"
    ),

just = "center",

gp = grid::gpar(
col = "black",
fontsize = annotation_row_font_size,
fontface = "bold"
    ),

width = grid::unit(
      3.5,
      "mm"
    )
  ),

  `n repetition` = ComplexHeatmap::anno_text(
    as.character(
      row_annotation_table$n_repetition
    ),

location = grid::unit(
      0.5,
      "npc"
    ),

just = "center",

gp = grid::gpar(
col = "black",
fontsize = annotation_row_font_size,
fontface = "bold"
    ),

width = grid::unit(
      4.0,
      "mm"
    )
  ),

  `Gene symbol` = ComplexHeatmap::anno_text(
    row_ids,

location = grid::unit(
      0,
      "npc"
    ),

just = "left",

gp = grid::gpar(
col = "black",
fontsize = annotation_row_font_size
    ),

width = gene_symbol_annotation_width
  ),

col = list(
Cluster = cluster_annotation_colors
  ),

simple_anno_size = grid::unit(
    4.2,
    "mm"
  ),

gap = grid::unit(
    0.60,
    "mm"
  ),

show_annotation_name = c(
Cluster = TRUE,
    `Max mean %` = TRUE,
    `FDR marker` = TRUE,
    `n repetition` = TRUE,
    `Gene symbol` = TRUE
  ),

annotation_label = c(
Cluster = "Cluster",
    `Max mean %` = "Max mean %",
    `FDR marker` = "FDR marker",
    `n repetition` = "n repetition",
    `Gene symbol` = "Gene symbol"
  ),

annotation_name_side = "top",

annotation_name_rot = c(
Cluster = 45,
    `Max mean %` = 45,
    `FDR marker` = 45,
    `n repetition` = 45,
    `Gene symbol` = 45
  ),

annotation_name_gp = grid::gpar(
fontsize = 8,
fontface = "bold"
  ),

annotation_legend_param = list(
Cluster = list(
title = "Source cluster",
labels = cluster_legend_labels,
at = cluster_factor_levels,
ncol = 1
    )
  )
)


# One global row clustering and one dendrogram.
# The source cluster modifies pairwise distances but does not impose a hard split.
hc_rows <- create_modified_row_hclust(
expression_matrix = zscore_matrix,
annotation_table = row_annotation_table,
base_distance = row_clustering_base_distance,
r_scale = row_clustering_r_scale,
same_cluster_bonus = row_clustering_same_cluster_bonus,
linkage_method = row_clustering_linkage_method
)


# ==============================================================================
# 14. Column annotation
# ==============================================================================

sex_colors <- c(
  "Male" = "#3C78D8",
  "Female" = "#C050A0"
)

group_colors <- c(
  "Neurotypical" = "grey70",
  "ASD" = "black"
)

top_annotation <- ComplexHeatmap::HeatmapAnnotation(
Group = sample_metadata$fmt_donor_group,
Sex = sample_metadata$sex,
col = list(
Group = group_colors,
Sex = sex_colors
  ),
simple_anno_size = grid::unit(4.2, "mm"),
annotation_name_side = "left",
annotation_name_gp = grid::gpar(
fontsize = 9,
fontface = "bold"
  ),
annotation_legend_param = list(
Group = list(
title = "FMT donor group",
ncol = 1
    ),
Sex = list(
title = "Sex",
ncol = 1
    )
  )
)


# ==============================================================================
# 15. Heatmap title and dimensions
# ==============================================================================

number_of_results <- nrow(significant_interaction)
number_of_unique_genes <- length(unique(significant_interaction$gene))
number_of_clusters <- length(significant_cluster_ids)
number_of_samples <- ncol(zscore_matrix)

heatmap_title_lines <- c(
  "Group x Sex interaction: significant genes per cluster",
  paste0(
    "Selection: FDR < ",
    fdr_threshold,
    " | ",
    number_of_results,
    " cluster-gene results | ",
    number_of_unique_genes,
    " unique genes | ",
    number_of_clusters,
    " clusters"
  ),
  "Input: sample-level TMM-normalized CPM from each cluster DGEList",
  "Transformation: log2(CPM + 1) -> row Z-score clipped to [-2, 2]",
  if (isTRUE(impute_missing_by_group_mean)) {
    paste0(
      "Missing sample-cluster CPM: imputed by mean within Sex x FMT donor group before log2",
      " | imputed values: ",
      number_imputed_values
    )
  } else {
    "Missing sample-cluster CPM retained as NA (shown in grey)"
  },
  paste0(
    "Columns: Male Neurotypical -> Male ASD -> Female Neurotypical -> Female ASD",
    " | ",
    number_of_samples,
    " samples"
  ),
  paste0(
    "Row clustering: Pearson correlation on row Z-scores",
    " | base distance d = ",
    row_clustering_base_distance,
    " | r_scale = ",
    row_clustering_r_scale
  ),
  paste0(
    "Same-cluster bonus = ",
    row_clustering_same_cluster_bonus,
    " -> same cluster: d x ",
    formatC(1 - row_clustering_same_cluster_bonus, format = "f", digits = 2),
    ", different clusters: d x ",
    formatC(1 + row_clustering_same_cluster_bonus, format = "f", digits = 2),
    " | linkage = ",
    row_clustering_linkage_method
  ),
  clustering_title
)

heatmap_title <- paste(
  heatmap_title_lines,
collapse = "\n"
)

row_font_size <- if (number_of_results <= 80L) {
  7.2
} else if (number_of_results <= 180L) {
  5.8
} else {
  4.8
}

row_height_mm <- if (number_of_results <= 80L) {
  3.1
} else if (number_of_results <= 180L) {
  2.35
} else {
  1.9
}

heatmap_body_height_mm <- number_of_results * row_height_mm
heatmap_body_width_mm <- number_of_samples * 6.2

pdf_width_inches <- 15
pdf_height_inches <- max(
  14,
  min(
    32,
    (heatmap_body_height_mm + 95) / 25.4
  )
)


# ==============================================================================
# 16. Create heatmap
# ==============================================================================

heatmap_color_function <- circlize::colorRamp2(
  c(-2, 0, 2),
  c("#2166AC", "white", "#B2182B")
)

heatmap_object <- ComplexHeatmap::Heatmap(
  zscore_matrix,
name = "Row Z-score",
col = heatmap_color_function,

top_annotation = top_annotation,
right_annotation = right_annotation,

cluster_columns = FALSE,
column_split = sample_metadata$combined_group,
cluster_column_slices = FALSE,
column_gap = grid::unit(1.2, "mm"),

cluster_rows = hc_rows,
row_dend_reorder = row_annotation_table$logFC,
row_gap = grid::unit(0, "mm"),
row_dend_width = grid::unit(18, "mm"),

show_column_names = TRUE,
column_names_side = "top",
column_names_rot = 45,
column_names_centered = TRUE,
column_names_gp = grid::gpar(
fontsize = 9,
fontface = "bold"
  ),
column_names_max_height = grid::unit(18, "mm"),

show_row_names = FALSE,

row_title_gp = grid::gpar(
fontsize = 8,
fontface = "bold"
  ),

na_col = "grey90",
rect_gp = grid::gpar(col = NA),
border = FALSE,
use_raster = FALSE,

width = grid::unit(heatmap_body_width_mm, "mm"),
height = grid::unit(heatmap_body_height_mm, "mm"),

column_title = heatmap_title,
column_title_side = "top",
column_title_gp = grid::gpar(
fontsize = 12,
fontface = "bold",
lineheight = 1.12
  ),

heatmap_legend_param = list(
title = "Row Z-score",
at = c(-2, -1, 0, 1, 2),
legend_height = grid::unit(46, "mm")
  )
)


# ==============================================================================
# 17. Export TSV files
# ==============================================================================

readr::write_tsv(
  significant_interaction,
  selected_results_tsv,
na = "NA"
)

readr::write_tsv(
  row_annotation_table,
  row_annotations_tsv,
na = "NA"
)

zscore_output <- tibble::tibble(
row_id = rownames(zscore_matrix)
) |>
  dplyr::bind_cols(
    tibble::as_tibble(
      as.data.frame(
        zscore_matrix,
check.names = FALSE
      ),
.name_repair = "minimal"
    )
  )

readr::write_tsv(
  zscore_output,
  zscore_matrix_tsv,
na = "NA"
)

sample_order_output <- sample_metadata |>
  dplyr::transmute(
sample_order = .data$sample_order,
sample_ID = .data$sample_ID,
sex = as.character(.data$sex),
fmt_donor_group = as.character(.data$fmt_donor_group),
combined_group = as.character(.data$combined_group)
  )

readr::write_tsv(
  sample_order_output,
  sample_order_tsv,
na = "NA"
)

summary_table <- tibble::tibble(
dataset_name = dataset_name,
clustering_name = clustering_name,
interaction_test_id = interaction_test_id,
fdr_threshold = fdr_threshold,
significant_cluster_gene_results = number_of_results,
unique_genes = number_of_unique_genes,
significant_clusters = paste(
    significant_cluster_ids,
collapse = ", "
  ),
number_of_significant_clusters = number_of_clusters,
samples_displayed = number_of_samples,
matrix_input = "sample-level TMM-normalized CPM from cluster DGEList objects",
imputation_enabled = impute_missing_by_group_mean,
imputation_method = if (isTRUE(impute_missing_by_group_mean)) {
    "mean CPM within Sex x FMT donor group before log2 transformation"
  } else {
    "none"
  },
missing_values_before_imputation = number_missing_before_imputation,
imputed_values = number_imputed_values,
rows_with_imputation = number_rows_with_imputation,
transformation = "log2(CPM + 1) -> row Z-score -> clip [-2, 2]",
row_clustering_base_distance = row_clustering_base_distance,
row_clustering_r_scale = row_clustering_r_scale,
row_clustering_same_cluster_bonus = row_clustering_same_cluster_bonus,
row_clustering_linkage_method = row_clustering_linkage_method,
output_pdf = heatmap_pdf
)

readr::write_tsv(
  summary_table,
  summary_tsv,
na = "NA"
)


# ==============================================================================
# 18. Save PDF
# ==============================================================================

fdr_marker_legend <- make_fdr_marker_legend(
  significant_interaction
)

message("\nLegend threshold counts:")

message(
  "FDR < 0.05: n = ",
  sum(
    !is.na(significant_interaction$FDR) &
      significant_interaction$FDR < 0.05
  )
)

message(
  "FDR < 0.01: n = ",
  sum(
    !is.na(significant_interaction$FDR) &
      significant_interaction$FDR < 0.01
  )
)

message(
  "FDR < 0.001: n = ",
  sum(
    !is.na(significant_interaction$FDR) &
      significant_interaction$FDR < 0.001
  )
)

message("\nWriting heatmap PDF:")
message(heatmap_pdf)
message(
  "PDF dimensions: ",
  round(pdf_width_inches, 2),
  " x ",
  round(pdf_height_inches, 2),
  " inches"
)

grDevices::pdf(
file = heatmap_pdf,
width = pdf_width_inches,
height = pdf_height_inches,
onefile = TRUE,
useDingbats = FALSE
)

ComplexHeatmap::draw(
  heatmap_object,
heatmap_legend_side = "right",
annotation_legend_side = "right",
merge_legends = TRUE,
legend_grouping = "original",
annotation_legend_list = list(
    fdr_marker_legend
  ),
padding = grid::unit(
    c(3, 3, 3, 3),
    "mm"
  )
)

grDevices::dev.off()


# ==============================================================================
# 19. Validate outputs and report
# ==============================================================================

expected_output_files <- c(
  heatmap_pdf,
  selected_results_tsv,
  row_annotations_tsv,
  zscore_matrix_tsv,
  sample_order_tsv,
  summary_tsv
)

missing_output_files <- expected_output_files[
  !file.exists(expected_output_files)
]

if (length(missing_output_files) > 0L) {
  stop(
    "Missing output file(s):\n",
    paste(missing_output_files, collapse = "\n"),
call. = FALSE
  )
}

empty_output_files <- expected_output_files[
  file.info(expected_output_files)$size == 0
]

if (length(empty_output_files) > 0L) {
  stop(
    "Empty output file(s):\n",
    paste(empty_output_files, collapse = "\n"),
call. = FALSE
  )
}

message("\nHeatmap completed successfully.")
message("Output directory:")
message(normalizePath(heatmap_output_dir, mustWork = TRUE))
message("\nHeatmap PDF:")
message(normalizePath(heatmap_pdf, mustWork = TRUE))

# ==============================================================================
# End
# ==============================================================================
